
package com.cbrc.smis.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for DocumentDetail data (i.e. 
 * com.cbrc.smis.form.DocumentDetailForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsDocumentDetailDelegate {


   /**
    * Create a new com.cbrc.smis.form.DocumentDetailForm object and persist (i.e. insert) it.
    *
    * @param   documentDetailForm   The object containing the data for the new com.cbrc.smis.form.DocumentDetailForm object
    * @exception   Exception   If the new com.cbrc.smis.form.DocumentDetailForm object cannot be created or persisted.
    */
   public static com.cbrc.smis.form.DocumentDetailForm create (com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = new com.cbrc.smis.hibernate.DocumentDetail ();
      TranslatorUtil.copyVoToPersistence(documentDetailPersistence, documentDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)session.save(documentDetailPersistence);
session.save(documentDetailPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(documentDetailPersistence, documentDetailForm);
      return documentDetailForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.smis.form.DocumentDetailForm object.
    *
    * @param   documentDetailForm   The com.cbrc.smis.form.DocumentDetailForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.smis.form.DocumentDetailForm object cannot be updated/persisted.
    */
   public static com.cbrc.smis.form.DocumentDetailForm update (com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = new com.cbrc.smis.hibernate.DocumentDetail ();
      TranslatorUtil.copyVoToPersistence(documentDetailPersistence, documentDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(documentDetailPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(documentDetailPersistence, documentDetailForm);
      return documentDetailForm;
   }

   /**
    * Retrieve an existing com.cbrc.smis.form.DocumentDetailForm object for editing.
    *
    * @param   documentDetailForm   The com.cbrc.smis.form.DocumentDetailForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.smis.form.DocumentDetailForm object cannot be retrieved.
    */
   public static com.cbrc.smis.form.DocumentDetailForm edit (com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = new com.cbrc.smis.hibernate.DocumentDetail ();
      TranslatorUtil.copyVoToPersistence(documentDetailPersistence, documentDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)session.load(com.cbrc.smis.hibernate.DocumentDetail.class, documentDetailPersistence.getDocDetailId());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(documentDetailPersistence, documentDetailForm);
      return documentDetailForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.smis.form.DocumentDetailForm object.
    *
    * @param   documentDetailForm   The com.cbrc.smis.form.DocumentDetailForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.smis.form.DocumentDetailForm object cannot be removed.
    */  
   public static void remove (com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = new com.cbrc.smis.hibernate.DocumentDetail ();
      TranslatorUtil.copyVoToPersistence(documentDetailPersistence, documentDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)session.load(com.cbrc.smis.hibernate.DocumentDetail.class, documentDetailPersistence.getDocDetailId());
session.delete(documentDetailPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.smis.form.DocumentDetailForm objects.
    *
    * @exception   Exception   If the com.cbrc.smis.form.DocumentDetailForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.DocumentDetail"));
tx.commit();
session.close();
      ArrayList documentDetail_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.DocumentDetailForm documentDetailFormTemp = new com.cbrc.smis.form.DocumentDetailForm();
         com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)it.next();
         TranslatorUtil.copyPersistenceToVo(documentDetailPersistence, documentDetailFormTemp);
         documentDetail_vos.add(documentDetailFormTemp);
      }
      retVals = documentDetail_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.smis.form.DocumentDetailForm objects for editing.
    *
    * @param   documentDetailForm   The com.cbrc.smis.form.DocumentDetailForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.smis.form.DocumentDetailForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.DocumentDetail as obj1 where obj1.docContent='" + documentDetailForm.getDocContent() + "'"));
tx.commit();
session.close();
      ArrayList documentDetail_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.DocumentDetailForm documentDetailFormTemp = new com.cbrc.smis.form.DocumentDetailForm();
         com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)it.next();
         TranslatorUtil.copyPersistenceToVo(documentDetailPersistence, documentDetailFormTemp);
         documentDetail_vos.add(documentDetailFormTemp);
      }
      retVals = documentDetail_vos;
      return retVals;
   }

   /**
    * This method will return all objects referenced by Document
    */
   public static List getDocument(com.cbrc.smis.form.DocumentDetailForm documentDetailForm) throws Exception {
      List retVals = new ArrayList();
      com.cbrc.smis.hibernate.DocumentDetail documentDetailPersistence = null;
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
documentDetailPersistence = (com.cbrc.smis.hibernate.DocumentDetail)session.load(com.cbrc.smis.hibernate.DocumentDetail.class, documentDetailPersistence.getDocDetailId());
tx.commit();
session.close();
retVals.add(documentDetailPersistence.getDocument());
      ArrayList DOC_ID_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.DocumentForm DOC_ID_Temp = new com.cbrc.smis.form.DocumentForm();
         com.cbrc.smis.hibernate.Document DOC_ID_PO = (com.cbrc.smis.hibernate.Document)it.next();
         TranslatorUtil.copyPersistenceToVo(DOC_ID_PO, DOC_ID_Temp);
         DOC_ID_vos.add(DOC_ID_Temp);
      }
      retVals = DOC_ID_vos;
      return retVals;
    }
}
