
package com.cbrc.org.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MActuOrg data (i.e. 
 * com.cbrc.org.form.MActuOrgForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMActuOrgDelegate {


   /**
    * Create a new com.cbrc.org.form.MActuOrgForm object and persist (i.e. insert) it.
    *
    * @param   mActuOrgForm   The object containing the data for the new com.cbrc.org.form.MActuOrgForm object
    * @exception   Exception   If the new com.cbrc.org.form.MActuOrgForm object cannot be created or persisted.
    */
   public static com.cbrc.org.form.MActuOrgForm create (com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = new com.cbrc.org.hibernate.MActuOrg ();
      TranslatorUtil.copyVoToPersistence(mActuOrgPersistence, mActuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: mActuOrgPersistence = (com.cbrc.org.hibernate.MActuOrg)session.save(mActuOrgPersistence);
session.save(mActuOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mActuOrgPersistence, mActuOrgForm);
      return mActuOrgForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.org.form.MActuOrgForm object.
    *
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.org.form.MActuOrgForm object cannot be updated/persisted.
    */
   public static com.cbrc.org.form.MActuOrgForm update (com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = new com.cbrc.org.hibernate.MActuOrg ();
      TranslatorUtil.copyVoToPersistence(mActuOrgPersistence, mActuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(mActuOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mActuOrgPersistence, mActuOrgForm);
      return mActuOrgForm;
   }

   /**
    * Retrieve an existing com.cbrc.org.form.MActuOrgForm object for editing.
    *
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.org.form.MActuOrgForm object cannot be retrieved.
    */
   public static com.cbrc.org.form.MActuOrgForm edit (com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = new com.cbrc.org.hibernate.MActuOrg ();
      TranslatorUtil.copyVoToPersistence(mActuOrgPersistence, mActuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
mActuOrgPersistence = (com.cbrc.org.hibernate.MActuOrg)session.load(com.cbrc.org.hibernate.MActuOrg.class, mActuOrgPersistence.getActuOrgTypeId());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mActuOrgPersistence, mActuOrgForm);
      return mActuOrgForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.org.form.MActuOrgForm object.
    *
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.org.form.MActuOrgForm object cannot be removed.
    */  
   public static void remove (com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = new com.cbrc.org.hibernate.MActuOrg ();
      TranslatorUtil.copyVoToPersistence(mActuOrgPersistence, mActuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
mActuOrgPersistence = (com.cbrc.org.hibernate.MActuOrg)session.load(com.cbrc.org.hibernate.MActuOrg.class, mActuOrgPersistence.getActuOrgTypeId());
session.delete(mActuOrgPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.org.form.MActuOrgForm objects.
    *
    * @exception   Exception   If the com.cbrc.org.form.MActuOrgForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MActuOrg"));
tx.commit();
session.close();
      ArrayList mActuOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MActuOrgForm mActuOrgFormTemp = new com.cbrc.org.form.MActuOrgForm();
         com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = (com.cbrc.org.hibernate.MActuOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mActuOrgPersistence, mActuOrgFormTemp);
         mActuOrg_vos.add(mActuOrgFormTemp);
      }
      retVals = mActuOrg_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.org.form.MActuOrgForm objects for editing.
    *
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.org.form.MActuOrgForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MActuOrg as obj1 where obj1.actuOrgTypeName='" + mActuOrgForm.getActuOrgTypeName() + "'"));
tx.commit();
session.close();
      ArrayList mActuOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MActuOrgForm mActuOrgFormTemp = new com.cbrc.org.form.MActuOrgForm();
         com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence = (com.cbrc.org.hibernate.MActuOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mActuOrgPersistence, mActuOrgFormTemp);
         mActuOrg_vos.add(mActuOrgFormTemp);
      }
      retVals = mActuOrg_vos;
      return retVals;
   }

}
