
package com.cbrc.org.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MOrgCode data (i.e. 
 * com.cbrc.org.form.MOrgCodeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMOrgCodeDelegate {


   /**
    * Create a new com.cbrc.org.form.MOrgCodeForm object and persist (i.e. insert) it.
    *
    * @param   mOrgCodeForm   The object containing the data for the new com.cbrc.org.form.MOrgCodeForm object
    * @exception   Exception   If the new com.cbrc.org.form.MOrgCodeForm object cannot be created or persisted.
    */
   public static com.cbrc.org.form.MOrgCodeForm create (com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = new com.cbrc.org.hibernate.MOrgCode ();
      TranslatorUtil.copyVoToPersistence(mOrgCodePersistence, mOrgCodeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: mOrgCodePersistence = (com.cbrc.org.hibernate.MOrgCode)session.save(mOrgCodePersistence);
session.save(mOrgCodePersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mOrgCodePersistence, mOrgCodeForm);
      return mOrgCodeForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.org.form.MOrgCodeForm object.
    *
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.org.form.MOrgCodeForm object cannot be updated/persisted.
    */
   public static com.cbrc.org.form.MOrgCodeForm update (com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = new com.cbrc.org.hibernate.MOrgCode ();
      TranslatorUtil.copyVoToPersistence(mOrgCodePersistence, mOrgCodeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(mOrgCodePersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mOrgCodePersistence, mOrgCodeForm);
      return mOrgCodeForm;
   }

   /**
    * Retrieve an existing com.cbrc.org.form.MOrgCodeForm object for editing.
    *
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.org.form.MOrgCodeForm object cannot be retrieved.
    */
   public static com.cbrc.org.form.MOrgCodeForm edit (com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = new com.cbrc.org.hibernate.MOrgCode ();
      TranslatorUtil.copyVoToPersistence(mOrgCodePersistence, mOrgCodeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
mOrgCodePersistence = (com.cbrc.org.hibernate.MOrgCode)session.load(com.cbrc.org.hibernate.MOrgCode.class, mOrgCodePersistence.getOrgCode());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mOrgCodePersistence, mOrgCodeForm);
      return mOrgCodeForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.org.form.MOrgCodeForm object.
    *
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.org.form.MOrgCodeForm object cannot be removed.
    */  
   public static void remove (com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = new com.cbrc.org.hibernate.MOrgCode ();
      TranslatorUtil.copyVoToPersistence(mOrgCodePersistence, mOrgCodeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
mOrgCodePersistence = (com.cbrc.org.hibernate.MOrgCode)session.load(com.cbrc.org.hibernate.MOrgCode.class, mOrgCodePersistence.getOrgCode());
session.delete(mOrgCodePersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.org.form.MOrgCodeForm objects.
    *
    * @exception   Exception   If the com.cbrc.org.form.MOrgCodeForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MOrgCode"));
tx.commit();
session.close();
      ArrayList mOrgCode_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MOrgCodeForm mOrgCodeFormTemp = new com.cbrc.org.form.MOrgCodeForm();
         com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = (com.cbrc.org.hibernate.MOrgCode)it.next();
         TranslatorUtil.copyPersistenceToVo(mOrgCodePersistence, mOrgCodeFormTemp);
         mOrgCode_vos.add(mOrgCodeFormTemp);
      }
      retVals = mOrgCode_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.org.form.MOrgCodeForm objects for editing.
    *
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.org.form.MOrgCodeForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MOrgCode as obj1 where obj1.regionId='" + mOrgCodeForm.getRegionId() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MOrgCode as obj1 where obj1.orgId='" + mOrgCodeForm.getOrgId() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MOrgCode as obj1 where obj1.orgName='" + mOrgCodeForm.getOrgName() + "'"));
tx.commit();
session.close();
      ArrayList mOrgCode_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MOrgCodeForm mOrgCodeFormTemp = new com.cbrc.org.form.MOrgCodeForm();
         com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence = (com.cbrc.org.hibernate.MOrgCode)it.next();
         TranslatorUtil.copyPersistenceToVo(mOrgCodePersistence, mOrgCodeFormTemp);
         mOrgCode_vos.add(mOrgCodeFormTemp);
      }
      retVals = mOrgCode_vos;
      return retVals;
   }

}
