package com.cbrc.org.adapter;

import com.fitech.net.form.OrgNetForm;
import com.fitech.net.hibernate.OrgNet;

/**
 * This is a utilitiy class to handle value object conversion between the 
 * backend persistence layer and the frontend action layer. It has a set of 
 * methods to handle conversions.
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class TranslatorUtil {


   /**
    * Copy data from a com.cbrc.org.form.MOrgForm value object into a com.cbrc.org.hibernate.MOrg object.
    *
    * @param   mOrgPersistence   The com.cbrc.org.hibernate.MOrg object into which the data is to be copied.
    * @param   mOrgForm   The com.cbrc.org.form.MOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MOrg mOrgPersistence, com.cbrc.org.form.MOrgForm mOrgForm) throws Exception {
      // Persistence layer specific implementation
          mOrgPersistence.setOrgId(mOrgForm.getOrgId());
              mOrgPersistence.setOrgName(mOrgForm.getOrgName());
                  mOrgPersistence.setOrgType(mOrgForm.getOrgType());
                  mOrgPersistence.setIsCorp(mOrgForm.getIsCorp());
                  mOrgPersistence.setOrgClsId(mOrgForm.getOrgClsId());
                  mOrgPersistence.setOrgCode(mOrgForm.getOrgCode());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MOrg object into a com.cbrc.org.form.MOrgForm value object.
    *
    * @param   mOrgPersistence   The com.cbrc.org.hibernate.MOrg object from which the data is to be copied.
    * @param   mOrgForm   The com.cbrc.org.form.MOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(
            com.cbrc.org.hibernate.MOrg mOrgPersistence,
            com.cbrc.org.form.MOrgForm mOrgForm) throws Exception {
        // Persistence layer specific implementation
        mOrgForm.setOrgId(mOrgPersistence.getOrgId());
        mOrgForm.setOrgName(mOrgPersistence.getOrgName());
        mOrgForm.setOrgType(mOrgPersistence.getOrgType());
        mOrgForm.setIsCorp(mOrgPersistence.getIsCorp());
        mOrgForm.setOrgClsId(mOrgPersistence.getOrgClsId());
        mOrgForm.setOrgCode(mOrgPersistence.getOrgCode());
       
    }
   protected static void copyPersistenceToVo(
           OrgNet mOrgPersistence,
           OrgNetForm mOrgForm) throws Exception {
       // Persistence layer specific implementation
       mOrgForm.setOrg_name( mOrgPersistence.getOrgName());
       mOrgForm.setOrg_id( mOrgPersistence.getOrgId());
       mOrgForm.setPre_org_id( mOrgPersistence.getPreOrgId() );
       mOrgForm.setOrg_type_id( mOrgPersistence.getOrgType().getOrgTypeId());
       mOrgForm.setRegion_id( mOrgPersistence.getRegion().getRegionId());
     
      
   }
   /**
    * Copy data from a com.cbrc.org.form.MOrgClForm value object into a com.cbrc.org.hibernate.MOrgCl object.
    *
    * @param   mOrgClPersistence   The com.cbrc.org.hibernate.MOrgCl object into which the data is to be copied.
    * @param   mOrgClForm   The com.cbrc.org.form.MOrgClForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MOrgCl mOrgClPersistence, com.cbrc.org.form.MOrgClForm mOrgClForm) throws Exception {
      // Persistence layer specific implementation
          mOrgClPersistence.setOrgClsId(mOrgClForm.getOrgClsId());
              mOrgClPersistence.setOrgClsNm(mOrgClForm.getOrgClsNm());
                  mOrgClPersistence.setOrgClsType(mOrgClForm.getOrgClsType());
         }

   
  

   
   
   /**
     * Copy data from a com.cbrc.org.form.MRegionForm value object into a
     * com.cbrc.org.hibernate.MRegion object.
     * 
     * @param mRegionPersistence
     *            The com.cbrc.org.hibernate.MRegion object into which the data
     *            is to be copied.
     * @param mRegionForm
     *            The com.cbrc.org.form.MRegionForm value object containing the
     *            data to be copied.
     */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MRegion mRegionPersistence, com.cbrc.org.form.MRegionForm mRegionForm) throws Exception {
      // Persistence layer specific implementation
          mRegionPersistence.setRegionId(mRegionForm.getRegionId());
              mRegionPersistence.setRegionTypId(mRegionForm.getRegionTypId());
                  mRegionPersistence.setRegionName(mRegionForm.getRegionName());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MRegion object into a com.cbrc.org.form.MRegionForm value object.
    *
    * @param   mRegionPersistence   The com.cbrc.org.hibernate.MRegion object from which the data is to be copied.
    * @param   mRegionForm   The com.cbrc.org.form.MRegionForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(
		   com.cbrc.org.hibernate.MRegion mRegionPersistence, 
		   com.cbrc.org.form.MRegionForm mRegionForm) throws Exception {
      // Persistence layer specific implementation
          mRegionForm.setRegionId(mRegionPersistence.getRegionId());
                      mRegionForm.setRegionTypId(mRegionPersistence.getRegionTypId());
                                mRegionForm.setRegionName(mRegionPersistence.getRegionName());
               }

   /**
    * Copy data from a com.cbrc.org.form.MSupvOrgForm value object into a com.cbrc.org.hibernate.MSupvOrg object.
    *
    * @param   mSupvOrgPersistence   The com.cbrc.org.hibernate.MSupvOrg object into which the data is to be copied.
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence, com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      // Persistence layer specific implementation
          mSupvOrgPersistence.setOrgId(mSupvOrgForm.getOrgId());
              mSupvOrgPersistence.setSupvOrgName(mSupvOrgForm.getSupvOrgName());
                  mSupvOrgPersistence.setPriorOrgId(mSupvOrgForm.getPriorOrgId());
                  mSupvOrgPersistence.setOrgCode(mSupvOrgForm.getOrgCode());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MSupvOrg object into a com.cbrc.org.form.MSupvOrgForm value object.
    *
    * @param   mSupvOrgPersistence   The com.cbrc.org.hibernate.MSupvOrg object from which the data is to be copied.
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence, com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      // Persistence layer specific implementation
          mSupvOrgForm.setOrgId(mSupvOrgPersistence.getOrgId());
                      mSupvOrgForm.setSupvOrgName(mSupvOrgPersistence.getSupvOrgName());
                                mSupvOrgForm.setPriorOrgId(mSupvOrgPersistence.getPriorOrgId());
                                mSupvOrgForm.setOrgCode(mSupvOrgPersistence.getOrgCode());
               }

   /**
    * Copy data from a com.cbrc.org.form.MRegionTypForm value object into a com.cbrc.org.hibernate.MRegionTyp object.
    *
    * @param   mRegionTypPersistence   The com.cbrc.org.hibernate.MRegionTyp object into which the data is to be copied.
    * @param   mRegionTypForm   The com.cbrc.org.form.MRegionTypForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MRegionTyp mRegionTypPersistence, com.cbrc.org.form.MRegionTypForm mRegionTypForm) throws Exception {
      // Persistence layer specific implementation
          mRegionTypPersistence.setRegionTypId(mRegionTypForm.getRegionTypId());
              mRegionTypPersistence.setRegionTypNm(mRegionTypForm.getRegionTypNm());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MRegionTyp object into a com.cbrc.org.form.MRegionTypForm value object.
    *
    * @param   mRegionTypPersistence   The com.cbrc.org.hibernate.MRegionTyp object from which the data is to be copied.
    * @param   mRegionTypForm   The com.cbrc.org.form.MRegionTypForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MRegionTyp mRegionTypPersistence, com.cbrc.org.form.MRegionTypForm mRegionTypForm) throws Exception {
      // Persistence layer specific implementation
          mRegionTypForm.setRegionTypId(mRegionTypPersistence.getRegionTypId());
                      mRegionTypForm.setRegionTypNm(mRegionTypPersistence.getRegionTypNm());
               }

   /**
    * Copy data from a com.cbrc.org.form.MActuOrgForm value object into a com.cbrc.org.hibernate.MActuOrg object.
    *
    * @param   mActuOrgPersistence   The com.cbrc.org.hibernate.MActuOrg object into which the data is to be copied.
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence, com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      // Persistence layer specific implementation
          mActuOrgPersistence.setActuOrgTypeId(mActuOrgForm.getActuOrgTypeId());
              mActuOrgPersistence.setActuOrgTypeName(mActuOrgForm.getActuOrgTypeName());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MActuOrg object into a com.cbrc.org.form.MActuOrgForm value object.
    *
    * @param   mActuOrgPersistence   The com.cbrc.org.hibernate.MActuOrg object from which the data is to be copied.
    * @param   mActuOrgForm   The com.cbrc.org.form.MActuOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MActuOrg mActuOrgPersistence, com.cbrc.org.form.MActuOrgForm mActuOrgForm) throws Exception {
      // Persistence layer specific implementation
          mActuOrgForm.setActuOrgTypeId(mActuOrgPersistence.getActuOrgTypeId());
                      mActuOrgForm.setActuOrgTypeName(mActuOrgPersistence.getActuOrgTypeName());
               }

   /**
    * Copy data from a com.cbrc.org.form.MVirOrgTypeForm value object into a com.cbrc.org.hibernate.MVirOrgType object.
    *
    * @param   mVirOrgTypePersistence   The com.cbrc.org.hibernate.MVirOrgType object into which the data is to be copied.
    * @param   mVirOrgTypeForm   The com.cbrc.org.form.MVirOrgTypeForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MVirOrgType mVirOrgTypePersistence, com.cbrc.org.form.MVirOrgTypeForm mVirOrgTypeForm) throws Exception {
      // Persistence layer specific implementation
          mVirOrgTypePersistence.setVirtuTypeId(mVirOrgTypeForm.getVirtuTypeId());
              mVirOrgTypePersistence.setVirtuTypeNm(mVirOrgTypeForm.getVirtuTypeNm());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MVirOrgType object into a com.cbrc.org.form.MVirOrgTypeForm value object.
    *
    * @param   mVirOrgTypePersistence   The com.cbrc.org.hibernate.MVirOrgType object from which the data is to be copied.
    * @param   mVirOrgTypeForm   The com.cbrc.org.form.MVirOrgTypeForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MVirOrgType mVirOrgTypePersistence, com.cbrc.org.form.MVirOrgTypeForm mVirOrgTypeForm) throws Exception {
      // Persistence layer specific implementation
          mVirOrgTypeForm.setVirtuTypeId(mVirOrgTypePersistence.getVirtuTypeId());
                      mVirOrgTypeForm.setVirtuTypeNm(mVirOrgTypePersistence.getVirtuTypeNm());
               }

   /**
    * Copy data from a com.cbrc.org.form.MOrgCodeForm value object into a com.cbrc.org.hibernate.MOrgCode object.
    *
    * @param   mOrgCodePersistence   The com.cbrc.org.hibernate.MOrgCode object into which the data is to be copied.
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence, com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      // Persistence layer specific implementation
          mOrgCodePersistence.setOrgCode(mOrgCodeForm.getOrgCode());
              mOrgCodePersistence.setRegionId(mOrgCodeForm.getRegionId());
                  mOrgCodePersistence.setOrgId(mOrgCodeForm.getOrgId());
                  mOrgCodePersistence.setOrgName(mOrgCodeForm.getOrgName());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MOrgCode object into a com.cbrc.org.form.MOrgCodeForm value object.
    *
    * @param   mOrgCodePersistence   The com.cbrc.org.hibernate.MOrgCode object from which the data is to be copied.
    * @param   mOrgCodeForm   The com.cbrc.org.form.MOrgCodeForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MOrgCode mOrgCodePersistence, com.cbrc.org.form.MOrgCodeForm mOrgCodeForm) throws Exception {
      // Persistence layer specific implementation
          mOrgCodeForm.setOrgCode(mOrgCodePersistence.getOrgCode());
                      mOrgCodeForm.setRegionId(mOrgCodePersistence.getRegionId());
                                mOrgCodeForm.setOrgId(mOrgCodePersistence.getOrgId());
                                mOrgCodeForm.setOrgName(mOrgCodePersistence.getOrgName());
               }

   /**
    * Copy data from a com.cbrc.org.form.MVirtuOrgForm value object into a com.cbrc.org.hibernate.MVirtuOrg object.
    *
    * @param   mVirtuOrgPersistence   The com.cbrc.org.hibernate.MVirtuOrg object into which the data is to be copied.
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence, com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      // Persistence layer specific implementation
          mVirtuOrgPersistence.setOrgId(mVirtuOrgForm.getOrgId());
              mVirtuOrgPersistence.setVirtualOrgName(mVirtuOrgForm.getVirtualOrgName());
                  mVirtuOrgPersistence.setStartDate(mVirtuOrgForm.getStartDate());
                  mVirtuOrgPersistence.setEndDate(mVirtuOrgForm.getEndDate());
                  mVirtuOrgPersistence.setOrgCode(mVirtuOrgForm.getOrgCode());
                  mVirtuOrgPersistence.setVirtuTypeId(mVirtuOrgForm.getVirtuTypeId());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MVirtuOrg object into a com.cbrc.org.form.MVirtuOrgForm value object.
    *
    * @param   mVirtuOrgPersistence   The com.cbrc.org.hibernate.MVirtuOrg object from which the data is to be copied.
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence, com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      // Persistence layer specific implementation
          mVirtuOrgForm.setOrgId(mVirtuOrgPersistence.getOrgId());
                      mVirtuOrgForm.setVirtualOrgName(mVirtuOrgPersistence.getVirtualOrgName());
                                mVirtuOrgForm.setStartDate(mVirtuOrgPersistence.getStartDate());
                                mVirtuOrgForm.setEndDate(mVirtuOrgPersistence.getEndDate());
                                mVirtuOrgForm.setOrgCode(mVirtuOrgPersistence.getOrgCode());
                                mVirtuOrgForm.setVirtuTypeId(mVirtuOrgPersistence.getVirtuTypeId());
               }

  
   /**
	 * Copy data from a com.cbrc.org.form.MVirOrgRltForm value object into a
	 * com.cbrc.org.hibernate.MVirOrgRlt object.
	 * 
	 * @param mVirOrgRltPersistence
	 *            The com.cbrc.org.hibernate.MVirOrgRlt object into which the
	 *            data is to be copied.
	 * @param mVirOrgRltForm
	 *            The com.cbrc.org.form.MVirOrgRltForm value object containing
	 *            the data to be copied.
	 */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MVirOrgRlt mVirOrgRltPersistence, com.cbrc.org.form.MVirOrgRltForm mVirOrgRltForm) throws Exception {
      // Persistence layer specific implementation
          //mVirOrgRltPersistence.setComp_id(mVirOrgRltForm.g.get.getVirOrgId());
            mVirOrgRltPersistence.setSumProp(mVirOrgRltForm.getSumProp());
                  mVirOrgRltPersistence.setStartDate(mVirOrgRltForm.getStartDate());
                  mVirOrgRltPersistence.setEndDate(mVirOrgRltForm.getEndDate());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MVirOrgRlt object into a com.cbrc.org.form.MVirOrgRltForm value object.
    *
    * @param   mVirOrgRltPersistence   The com.cbrc.org.hibernate.MVirOrgRlt object from which the data is to be copied.
    * @param   mVirOrgRltForm   The com.cbrc.org.form.MVirOrgRltForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MVirOrgRlt mVirOrgRltPersistence, com.cbrc.org.form.MVirOrgRltForm mVirOrgRltForm) throws Exception {
      // Persistence layer specific implementation
         // mVirOrgRltForm.setVirOrgId(mVirOrgRltPersistence.getVirOrgId());
           // mVirOrgRltForm.setOrgId(mVirOrgRltPersistence.getOrgId());
                      mVirOrgRltForm.setSumProp(mVirOrgRltPersistence.getSumProp());
                                mVirOrgRltForm.setStartDate(mVirOrgRltPersistence.getStartDate());
                                mVirOrgRltForm.setEndDate(mVirOrgRltPersistence.getEndDate());
               }

   /**
    * Copy data from a com.cbrc.org.form.MToRepOrgForm value object into a com.cbrc.org.hibernate.MToRepOrg object.
    *
    * @param   mToRepOrgPersistence   The com.cbrc.org.hibernate.MToRepOrg object into which the data is to be copied.
    * @param   mToRepOrgForm   The com.cbrc.org.form.MToRepOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MToRepOrg mToRepOrgPersistence, com.cbrc.org.form.MToRepOrgForm mToRepOrgForm) throws Exception {
      // Persistence layer specific implementation
          mToRepOrgPersistence.setOrgId(mToRepOrgForm.getOrgId());
              mToRepOrgPersistence.setOrgName(mToRepOrgForm.getOrgName());
                  mToRepOrgPersistence.setStartDate(mToRepOrgForm.getStartDate());
                  mToRepOrgPersistence.setEndDate(mToRepOrgForm.getEndDate());
                  mToRepOrgPersistence.setLicence(mToRepOrgForm.getLicence());
                  mToRepOrgPersistence.setOrgCode(mToRepOrgForm.getOrgCode());
                  mToRepOrgPersistence.setOrgClsId(mToRepOrgForm.getOrgClsId());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MToRepOrg object into a com.cbrc.org.form.MToRepOrgForm value object.
    *
    * @param   mToRepOrgPersistence   The com.cbrc.org.hibernate.MToRepOrg object from which the data is to be copied.
    * @param   mToRepOrgForm   The com.cbrc.org.form.MToRepOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MToRepOrg mToRepOrgPersistence, com.cbrc.org.form.MToRepOrgForm mToRepOrgForm) throws Exception {
      // Persistence layer specific implementation
          mToRepOrgForm.setOrgId(mToRepOrgPersistence.getOrgId());
          mToRepOrgForm.setOrgName(mToRepOrgPersistence.getOrgName());
          mToRepOrgForm.setStartDate(mToRepOrgPersistence.getStartDate());
                                mToRepOrgForm.setEndDate(mToRepOrgPersistence.getEndDate());
                                mToRepOrgForm.setLicence(mToRepOrgPersistence.getLicence());
                                mToRepOrgForm.setOrgCode(mToRepOrgPersistence.getOrgCode());
                                mToRepOrgForm.setOrgClsId(mToRepOrgPersistence.getOrgClsId());
               }

   /**
    * Copy data from a com.cbrc.org.form.MFinaOrgForm value object into a com.cbrc.org.hibernate.MFinaOrg object.
    *
    * @param   mFinaOrgPersistence   The com.cbrc.org.hibernate.MFinaOrg object into which the data is to be copied.
    * @param   mFinaOrgForm   The com.cbrc.org.form.MFinaOrgForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.org.hibernate.MFinaOrg mFinaOrgPersistence, com.cbrc.org.form.MFinaOrgForm mFinaOrgForm) throws Exception {
      // Persistence layer specific implementation
          mFinaOrgPersistence.setFinaOrgCode(mFinaOrgForm.getFinaOrgCode());
              mFinaOrgPersistence.setFinaOrgNm(mFinaOrgForm.getFinaOrgNm());
                  mFinaOrgPersistence.setLicence(mFinaOrgForm.getLicence());
                  mFinaOrgPersistence.setAddress(mFinaOrgForm.getAddress());
                  mFinaOrgPersistence.setOrgId(mFinaOrgForm.getOrgId());
                  mFinaOrgPersistence.setCorpAddress(mFinaOrgForm.getCorpAddress());
                  mFinaOrgPersistence.setOpenDate(mFinaOrgForm.getOpenDate());
                  mFinaOrgPersistence.setBankStyle(mFinaOrgForm.getBankStyle());
                  mFinaOrgPersistence.setCorpName(mFinaOrgForm.getCorpName());
         }

   /**
    * Copy data from a com.cbrc.org.hibernate.MFinaOrg object into a com.cbrc.org.form.MFinaOrgForm value object.
    *
    * @param   mFinaOrgPersistence   The com.cbrc.org.hibernate.MFinaOrg object from which the data is to be copied.
    * @param   mFinaOrgForm   The com.cbrc.org.form.MFinaOrgForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.org.hibernate.MFinaOrg mFinaOrgPersistence, com.cbrc.org.form.MFinaOrgForm mFinaOrgForm) throws Exception {
      // Persistence layer specific implementation
          mFinaOrgForm.setFinaOrgCode(mFinaOrgPersistence.getFinaOrgCode());
                      mFinaOrgForm.setFinaOrgNm(mFinaOrgPersistence.getFinaOrgNm());
                                mFinaOrgForm.setLicence(mFinaOrgPersistence.getLicence());
                                mFinaOrgForm.setAddress(mFinaOrgPersistence.getAddress());
                                mFinaOrgForm.setOrgId(mFinaOrgPersistence.getOrgId());
                                mFinaOrgForm.setCorpAddress(mFinaOrgPersistence.getCorpAddress());
                                mFinaOrgForm.setOpenDate(mFinaOrgPersistence.getOpenDate());
                                mFinaOrgForm.setBankStyle(mFinaOrgPersistence.getBankStyle());
                                mFinaOrgForm.setCorpName(mFinaOrgPersistence.getCorpName());
               }
   
   protected static void copyPersistenceToVo(
		   com.cbrc.org.hibernate.MOrgCl mOrgClPersistence, 
		   com.cbrc.org.form.MOrgClForm mOrgClForm) throws Exception {
	      // Persistence layer specific implementation
	        mOrgClForm.setOrgClsId(mOrgClPersistence.getOrgClsId());
			mOrgClForm.setOrgClsNm(mOrgClPersistence.getOrgClsNm());
			mOrgClForm.setOrgClsType(mOrgClPersistence.getOrgClsType());
		}

   
   
}
