package com.fitech.net.hibernate;



/**
 * CollectReal generated by MyEclipse - Hibernate Tools
 */

public class CollectReal  implements java.io.Serializable {


    // Fields    

     private Integer crId;
     private String childRepId;
     private String versionId;
     private Integer dataRangeId;
     private Integer repFreqId;
     private Integer curId;
     private String realRepId;
     private String realVerId;
     private Integer isOrder;
     private String orderColId;
     private Integer totalRow;
     private Integer startRow;


    // Constructors

    /** default constructor */
    public CollectReal() {
    }

    
    /** full constructor */
    public CollectReal(String childRepId, String versionId, Integer dataRangeId, Integer repFreqId, Integer curId, String realRepId, Integer isOrder, String orderColId, Integer totalRow, Integer startRow) {
        this.childRepId = childRepId;
        this.versionId = versionId;
        this.dataRangeId = dataRangeId;
        this.repFreqId = repFreqId;
        this.curId = curId;
        this.realRepId = realRepId;
        this.isOrder = isOrder;
        this.orderColId = orderColId;
        this.totalRow = totalRow;
        this.startRow = startRow;
    }

   
    // Property accessors

    public Integer getCrId() {
        return this.crId;
    }
    
    public void setCrId(Integer crId) {
        this.crId = crId;
    }

    public String getChildRepId() {
        return this.childRepId;
    }
    
    public void setChildRepId(String childRepId) {
        this.childRepId = childRepId;
    }

    public String getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }

    public Integer getDataRangeId() {
        return this.dataRangeId;
    }
    
    public void setDataRangeId(Integer dataRangeId) {
        this.dataRangeId = dataRangeId;
    }

    public Integer getRepFreqId() {
        return this.repFreqId;
    }
    
    public void setRepFreqId(Integer repFreqId) {
        this.repFreqId = repFreqId;
    }

    public Integer getCurId() {
        return this.curId;
    }
    
    public void setCurId(Integer curId) {
        this.curId = curId;
    }

    public String getRealRepId() {
        return this.realRepId;
    }
    
    public void setRealRepId(String realRepId) {
        this.realRepId = realRepId;
    }

    public Integer getIsOrder() {
        return this.isOrder;
    }
    
    public void setIsOrder(Integer isOrder) {
        this.isOrder = isOrder;
    }

    public String getOrderColId() {
        return this.orderColId;
    }
    
    public void setOrderColId(String orderColId) {
        this.orderColId = orderColId;
    }

    public Integer getTotalRow() {
        return this.totalRow;
    }
    
    public void setTotalRow(Integer totalRow) {
        this.totalRow = totalRow;
    }

    public Integer getStartRow() {
        return this.startRow;
    }
    
    public void setStartRow(Integer startRow) {
        this.startRow = startRow;
    }


	public String getRealVerId()
	{
		return realVerId;
	}


	public void setRealVerId(String realVerId)
	{
		this.realVerId = realVerId;
	}
   








}