package com.fitech.net.hibernate;



/**
 * CollectDetail generated by MyEclipse - Hibernate Tools
 */

public class CollectDetail  implements java.io.Serializable {


    // Fields    

     private Integer cdId;
     private String childRepId;
     private String versionId;
     private String cellName;
     private Integer cdType;
     private String cdSql;


    // Constructors

    /** default constructor */
    public CollectDetail() {
    }

    
    /** full constructor */
    public CollectDetail(String childRepId, String versionId, String cellName, Integer cdType, String cdSql) {
        this.childRepId = childRepId;
        this.versionId = versionId;
        this.cellName = cellName;
        this.cdType = cdType;
        this.cdSql = cdSql;
    }

   
    // Property accessors

    public Integer getCdId() {
        return this.cdId;
    }
    
    public void setCdId(Integer cdId) {
        this.cdId = cdId;
    }

    public String getChildRepId() {
        return this.childRepId;
    }
    
    public void setChildRepId(String childRepId) {
        this.childRepId = childRepId;
    }

    public String getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }

    public String getcellName() {
        return this.cellName;
    }
    
    public void setcellName(String cellName) {
        this.cellName = cellName;
    }

    public Integer getCdType() {
        return this.cdType;
    }
    
    public void setCdType(Integer cdType) {
        this.cdType = cdType;
    }

    public String getCdSql() {
        return this.cdSql;
    }
    
    public void setCdSql(String cdSql) {
        this.cdSql = cdSql;
    }
   








}