/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jun 29 14:32:57 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.fitech.net.hibernate;
import java.io.Serializable;

/**
 * A class that represents a row in the ORG_TYPE table. 
 * You can customize the behavior of this class by editing the class, {@link OrgType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class OrgType 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer orgTypeId;

    /** The value of the mRegionSet one-to-many association. */
    private java.util.Set regionSet;

    /** The value of the orgSet one-to-many association. */
    private java.util.Set orgSet;

    /** The value of the simple orgTypeName property. */
    private java.lang.String orgTypeName;

    /**
     * Simple constructor of AbstractOrgType instances.
     */
    public OrgType()
    {
    }

    /**
     * Constructor of AbstractOrgType instances given a simple primary key.
     * @param orgTypeId
     */
    public OrgType(java.lang.Integer orgTypeId)
    {
        this.setOrgTypeId(orgTypeId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getOrgTypeId()
    {
        return orgTypeId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param orgTypeId
     */
    public void setOrgTypeId(java.lang.Integer orgTypeId)
    {
        this.hashValue = 0;
        this.orgTypeId = orgTypeId;
    }

    /**
     * Return the value of the ORG_TYPE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getOrgTypeName()
    {
        return this.orgTypeName;
    }

    /**
     * Set the value of the ORG_TYPE_NAME column.
     * @param orgTypeName
     */
    public void setOrgTypeName(java.lang.String orgTypeName)
    {
        this.orgTypeName = orgTypeName;
    }

    /**
	 * @return Returns the regionSet.
	 */
	public java.util.Set getRegionSet() {
		return regionSet;
	}

	/**
	 * @param regionSet The regionSet to set.
	 */
	public void setRegionSet(java.util.Set regionSet) {
		this.regionSet = regionSet;
	}

	/**
     * Return the value of the ORG_TYPE_ID collection.
     * @return Org
     */
    public java.util.Set getOrgSet()
    {
        return this.orgSet;
    }

    /**
     * Set the value of the ORG_TYPE_ID collection.
     * @param orgSet
     */
    public void setOrgSet(java.util.Set orgSet)
    {
        this.orgSet = orgSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof OrgType))
            return false;
        OrgType that = (OrgType) rhs;
        if (this.getOrgTypeId() == null || that.getOrgTypeId() == null)
            return false;
        return (this.getOrgTypeId().equals(that.getOrgTypeId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int orgTypeIdValue = this.getOrgTypeId() == null ? 0 : this.getOrgTypeId().hashCode();
            result = result * 37 + orgTypeIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
