
package com.gather.adapter;

import net.sf.hibernate.Session;

import com.gather.common.Log;
import com.gather.dao.DBConn;
/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MCellForm data (i.e. 
 * com.gather.struts.MCellFormForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMCellFormDelegate {


   /**
    * Create a new com.gather.struts.MCellFormForm object and persist (i.e. insert) it.
    *
    * @param   mCellFormForm   The object containing the data for the new com.gather.struts.MCellFormForm object
    * @exception   Exception   If the new com.gather.struts.MCellFormForm object cannot be created or persisted.
    */
   public static boolean create (com.gather.struts.forms.MCellFormForm mCellFormForm) throws Exception {
      com.gather.hibernate.MCellForm mCellFormPersistence = new com.gather.hibernate.MCellForm ();
      try{
      TranslatorUtil.copyVoToPersistence(mCellFormPersistence, mCellFormForm);
      DBConn conn=new DBConn();
      Session session=conn.beginTransaction();
      session.save(mCellFormPersistence);
      conn.endTransaction(true);
      return true;
      }catch(Exception e)
      {
    	  new Log(StrutsMCellFormDelegate.class).info(":::class:StrutsMCellFormDelegate --  method: create “Ï≥££∫"+e.getMessage());
    	  throw e;
      }
   }
}
