
package com.gather.adapter;


/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MCurr data (i.e. 
 * com.gather.struts.forms.MCurrForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMCurrDelegate {


//暂时没有任何方法
}
