
package com.gather.adapter;

import java.util.ArrayList;
import java.util.List;

import net.sf.hibernate.Session;

import com.gather.common.Log;
import com.gather.dao.DBConn;
import com.gather.hibernate.MUser;
import com.gather.struts.forms.MUserForm;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for Calendar data (i.e. 
 * com.gather.struts.CalendarForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMUserDelegate {
	
	public static MUserForm checkUser(String userId,String pw){
		DBConn conn=new DBConn();
		Session session=conn.openSession();
		String hsql="from com.gather.hibernate.MUser as obj where obj.userId='"+userId.trim()+"'"+
		             " and obj.password='"+pw+"'";
		// System.out.println("user hsql is: "+hsql);
		List list=new ArrayList();
		MUserForm myForm=null;
	      try{
		      list.addAll(session.find(hsql));
  	          session.close();
  	          // System.out.println("-----------list.size() is: "+list.size());
	      if(list!=null && list.size()>0){
	    	  myForm=new MUserForm();
	    	  MUser myPersistence = (MUser)list.get(0);
	    	  TranslatorUtil.copyPersistenceToVo(myPersistence,myForm);
	      }
	      }catch(Exception e){
	    	  new Log(StrutsMUserDelegate.class).info(":::class:StrutsMUserDelegate --  method:checkUser “Ï≥££∫"+e.getMessage());
	    	  e.printStackTrace();}
	      finally{
	    	  try{
	    		  session.close();
	    	  }catch(Exception e){e.printStackTrace();}
	      }
	      return myForm;
	} 
}
