
package com.gather.adapter;

import net.sf.hibernate.Session;

import com.gather.common.Log;
import com.gather.dao.DBConn;
/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for Calendar data (i.e. 
 * com.gather.struts.CalendarForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsCalendarDelegate {


   /**
    * Create a new com.gather.struts.CalendarForm object and persist (i.e. insert) it.
    *
    * @param   calendarForm   The object containing the data for the new com.gather.struts.CalendarForm object
    * @exception   Exception   If the new com.gather.struts.CalendarForm object cannot be created or persisted.
    */
   public static boolean create (com.gather.struts.forms.CalendarForm calendarForm) throws Exception {
      com.gather.hibernate.Calendar calendarPersistence = new com.gather.hibernate.Calendar ();
      try{
      TranslatorUtil.copyVoToPersistence(calendarPersistence, calendarForm);
      DBConn conn=new DBConn();
      Session session=conn.beginTransaction();
      session.save(calendarPersistence);
      conn.endTransaction(true);
      return true;
      }catch(Exception e)
      {
    	  new Log(StrutsCalendarDelegate.class).info(":::class:StrutsCalendarDelegate --  method: create “Ï≥££∫"+e.getMessage());
    	  throw e;
      }
   }


}
