
package com.gather.adapter;

import net.sf.hibernate.Session;

import com.gather.common.Log;
import com.gather.dao.DBConn;
/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for CalendarType data (i.e. 
 * com.gather.struts.CalendarTypeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsCalendarTypeDelegate {


   /**
    * Create a new com.gather.struts.CalendarTypeForm object and persist (i.e. insert) it.
    *
    * @param   calendarTypeForm   The object containing the data for the new com.gather.struts.CalendarTypeForm object
    * @exception   Exception   If the new com.gather.struts.CalendarTypeForm object cannot be created or persisted.
    */
   public static boolean  create (com.gather.struts.forms.CalendarTypeForm calendarTypeForm) throws Exception {
      com.gather.hibernate.CalendarType calendarTypePersistence = new com.gather.hibernate.CalendarType ();
      try{
      TranslatorUtil.copyVoToPersistence(calendarTypePersistence, calendarTypeForm);
      DBConn conn=new DBConn();
      Session session=conn.beginTransaction();
      session.save(calendarTypePersistence);
      conn.endTransaction(true);
      return true;
      }catch(Exception e)
      {
    	  new Log(StrutsCalendarTypeDelegate.class).info(":::class:StrutsCalendarTypeDelegate --  method: create “Ï≥££∫"+e.getMessage());
    	  throw e;
      }
   }

 
}
