package com.gather.adapter;

import net.sf.hibernate.Hibernate;

import com.gather.hibernate.CalendarDetailPK;
import com.gather.hibernate.Cell2Form;
import com.gather.hibernate.DataValidateInfoPK;
import com.gather.hibernate.Log;
import com.gather.hibernate.MActuRepPK;
import com.gather.hibernate.MChildReport;
import com.gather.hibernate.MChildReportPK;
import com.gather.hibernate.MCurUnit;
import com.gather.hibernate.MCurr;
import com.gather.hibernate.MDataRgType;
import com.gather.hibernate.MMainRep;
import com.gather.hibernate.MOrg;
import com.gather.hibernate.MRepRangePK;
import com.gather.hibernate.MRepType;
import com.gather.hibernate.MappingRelationPK;
import com.gather.hibernate.RepRangeDownLogPK;
import com.gather.hibernate.ReportDataPK;
import com.gather.struts.forms.Cell2FormForm;
import com.gather.struts.forms.CopyLogform;
import com.gather.struts.forms.RealReportForm;

/**
 * This is a utilitiy class to handle value object conversion between the
 * backend persistence layer and the frontend action layer. It has a set of
 * methods to handle conversions.
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class TranslatorUtil {
	
	protected static void copyVoToPersistence(Cell2Form cell2formPersistence,Cell2FormForm cell2FormForm) throws Exception{
		cell2formPersistence.setCell2FormId(cell2FormForm.getCell2FormId());
		cell2formPersistence.setCellFormId(cell2FormForm.getCellFormId());
		cell2formPersistence.setChildRepId(cell2FormForm.getChildRepId());
		cell2formPersistence.setVersionId(cell2FormForm.getVersionId());
	}
	
	protected static void copyVoToPersistence(
			com.gather.hibernate.MUser mUserPersistence,
			com.gather.struts.forms.MUserForm mUserForm) throws Exception {
		mUserPersistence.setUserId(mUserForm.getUserId());
		mUserPersistence.setName(mUserForm.getName());
		mUserPersistence.setDept(mUserForm.getDept());
		mUserPersistence.setPassword(mUserForm.getPassword());
		if (mUserPersistence.getMOrg() != null) {
			mUserPersistence.getMOrg().setOrgId(mUserForm.getUserId());
		}
	}

	/**
	 * Copy data from a com.gather.hibernate.Log object into a
	 * com.gather.struts.LogForm value object.
	 * 
	 * @param logPersistence
	 *            The com.gather.hibernate.Log object from which the data is to
	 *            be copied.
	 * @param logForm
	 *            The com.gather.struts.LogForm value object into which the data
	 *            is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MUser mUserPersistence,
			com.gather.struts.forms.MUserForm mUserForm) throws Exception {
		mUserForm.setUserId(mUserPersistence.getUserId());
		mUserForm.setName(mUserPersistence.getName());
		mUserForm.setDept(mUserPersistence.getDept());
		mUserForm.setPassword(mUserPersistence.getPassword());
		if (mUserPersistence.getMOrg() != null) {
			mUserForm.setOrgId(mUserPersistence.getMOrg().getOrgId());
		}
	}

	protected static void copyVoToPersistence(
			com.gather.struts.forms.HandleReferFileForm referForm,
			com.gather.hibernate.Report report) {
		if (report.getMDataRgType() == null) {
			report.setMDataRgType(new com.gather.hibernate.MDataRgType());
		}
		report.getMDataRgType().setDataRangeId(referForm.getDataRange());
		report.setFrequency(referForm.getFrequency());
		if (report.getMOrg() == null) {
			report.setMOrg(new MOrg());
		}
		report.getMOrg().setOrgId(referForm.getOrgId());
		if (report.getMChildReport() == null) {
			com.gather.hibernate.MChildReport mcr = new com.gather.hibernate.MChildReport();
			mcr.setComp_id(new com.gather.hibernate.MChildReportPK(referForm
					.getReportId(), referForm.getVersion()));
			report.setMChildReport(mcr);

		} else {
			report.getMChildReport().getComp_id().setChildRepId(
					referForm.getReportId());
			report.getMChildReport().getComp_id().setVersionId(
					referForm.getVersion());
		}

		report.setRepName(referForm.getReportName());
		report.setTerm(referForm.getTerms());
		report.setYear(new Integer(referForm.getYear()));

	}

	/**
	 * 得到代报关系的机构的信息，返回机构form类
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MappingRelation MapRelationPersistence,
			com.gather.struts.forms.MOrgForm orgForm) throws Exception {
		// Persistence layer specific implementation
		orgForm.setOrgId(MapRelationPersistence.getComp_id().getReplaceOrgId());
	}

	/**
	 * 得到代报关系的机构的信息，返回机构form类
	 */
	protected static void copyPersistenceToVo(Log logPersistence,
			CopyLogform logForm) throws Exception {
		logForm.setLogId(logPersistence.getLogId());
		logForm.setUserName(logPersistence.getUserName());
		logForm.setLogTime(logPersistence.getLogTime());
		logForm.setOperation(logPersistence.getOperation());
		logForm.setOrgId(logPersistence.getOrgId());
		logForm.setMemo(logPersistence.getMemo());
		if (logPersistence.getLogType() != null) {
			logForm.setLogTypeId(logPersistence.getLogType().getLogTypeId());
		}
		if (logPersistence.getLogType() != null) {
			logForm.setLogType(logPersistence.getLogType().getLogType());
		}
	}

	/**
	 * @author linfeng
	 * @param com.gather.hibernate.MActuRep
	 * @param com.gather.struts.forms.MChildReportForm
	 * @return com.gather.struts.forms.RealReportForm
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MActuRep mActuRepPersistence,
			com.gather.struts.forms.MChildReportForm mChildReportForm,
			com.gather.struts.forms.RealReportForm realReportForm) {
		// Persistence layer specific implementation
		// 实际报表数据
		realReportForm.setDataRangeId(mActuRepPersistence.getComp_id()
				.getDataRangeId());
		if (mActuRepPersistence.getMDataRgType() != null) {
			realReportForm.setDataRangeName(mActuRepPersistence
					.getMDataRgType().getDataRgDesc());
		}
		realReportForm.setRepFreqId(mActuRepPersistence.getComp_id()
				.getRepFreqId());
		if (mActuRepPersistence.getMRepFreq() != null) {
			realReportForm.setRepFreqName(mActuRepPersistence.getMRepFreq()
					.getRepFreqName());
		}
		realReportForm.setDelayTime(mActuRepPersistence.getDelayTime());
		realReportForm.setNormalTime(mActuRepPersistence.getNormalTime());
		// 子报表数据
		realReportForm.setChildRepId(mChildReportForm.getChildRepId());
		realReportForm.setCurUnit(mChildReportForm.getCurUnit());
		realReportForm.setStartDate(mChildReportForm.getStartDate());
		realReportForm.setEndDate(mChildReportForm.getEndDate());
		realReportForm.setVersionId(mChildReportForm.getVersionId());
		realReportForm.setFormatTempId(mChildReportForm.getFormatTempId());
		realReportForm.setRepId(mChildReportForm.getRepId());
		realReportForm.setReportName(mChildReportForm.getReportName());
	}

	/**
	 * @author linfeng
	 * @param com.gather.hibernate.MActuRep
	 * @param com.gather.struts.forms.RealReportForm
	 * @return com.gather.struts.forms.RealReportForm
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MActuRep mActuRepPersistence,
			com.gather.struts.forms.RealReportForm realReportFormSource,
			com.gather.struts.forms.RealReportForm realReportForm) {
		// Persistence layer specific implementation
		// 实际报表数据
		realReportForm.setDataRangeId(mActuRepPersistence.getComp_id()
				.getDataRangeId());
		if (mActuRepPersistence.getMDataRgType() != null) {
			realReportForm.setDataRangeName(mActuRepPersistence
					.getMDataRgType().getDataRgDesc());
		}
		realReportForm.setRepFreqId(mActuRepPersistence.getComp_id()
				.getRepFreqId());
		if (mActuRepPersistence.getMRepFreq() != null) {
			realReportForm.setRepFreqName(mActuRepPersistence.getMRepFreq()
					.getRepFreqName());
		}
		realReportForm.setDelayTime(mActuRepPersistence.getDelayTime());
		realReportForm.setNormalTime(mActuRepPersistence.getNormalTime());
		// 子报表数据
		realReportForm.setChildRepId(realReportFormSource.getChildRepId());
		realReportForm.setCurUnit(realReportFormSource.getCurUnit());
		realReportForm.setStartDate(realReportFormSource.getStartDate());
		realReportForm.setEndDate(realReportFormSource.getEndDate());
		realReportForm.setVersionId(realReportFormSource.getVersionId());
		realReportForm.setFormatTempId(realReportFormSource.getFormatTempId());
		realReportForm.setRepId(realReportFormSource.getRepId());
		realReportForm.setReportName(realReportFormSource.getReportName());
	}

	/**
	 * Copy data from a com.gather.struts.ReportDataForm value object into a
	 * com.gather.hibernate.ReportData object.
	 * 
	 * @param reportDataPersistence
	 *            The com.gather.hibernate.ReportData object into which the data
	 *            is to be copied.
	 * @param reportDataForm
	 *            The com.gather.struts.ReportDataForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.ReportData reportDataPersistence,
			com.gather.struts.forms.ReportDataForm reportDataForm)
			throws Exception {
		// Persistence layer specific implementation
		if(reportDataForm.getPdf()!=null) 
			reportDataPersistence.setPdf(Hibernate.createBlob(reportDataForm.getPdf().getBinaryStream()));
		
		if(reportDataForm.getNote()!=null)
			reportDataPersistence.setNote(Hibernate.createBlob(reportDataForm.getNote().getBinaryStream()));
		
		if(reportDataForm.getXml()!=null)
			reportDataPersistence.setXml(Hibernate.createBlob(reportDataForm.getXml().getBinaryStream()));
		
		/*
		 * reportDataPersistence.getComp_id().setChildRepId(reportDataForm.getChildRepId());
		 * reportDataPersistence.getComp_id().setVersionId(reportDataForm.getVersionId());
		 */
		ReportDataPK reportDataPK = new ReportDataPK();
		reportDataPK.setChildRepId(reportDataForm.getChildRepId());
		reportDataPK.setVersionId(reportDataForm.getVersionId());
		reportDataPersistence.setComp_id(reportDataPK);
	}

	/**
	 * Copy data from a com.gather.hibernate.ReportData object into a
	 * com.gather.struts.ReportDataForm value object.
	 * 
	 * @param reportDataPersistence
	 *            The com.gather.hibernate.ReportData object from which the data
	 *            is to be copied.
	 * @param reportDataForm
	 *            The com.gather.struts.ReportDataForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.ReportData reportDataPersistence,
			com.gather.struts.forms.ReportDataForm reportDataForm)
			throws Exception {
		// Persistence layer specific implementation
		reportDataForm.setPdf(reportDataPersistence.getPdf());
		reportDataForm.setNote(reportDataPersistence.getNote());
		reportDataForm.setXml(reportDataPersistence.getXml());
		reportDataForm.setChildRepId(reportDataPersistence.getComp_id()
				.getChildRepId());
		reportDataForm.setVersionId(reportDataPersistence.getComp_id()
				.getVersionId());
	}

	/**
	 * Copy data from a com.gather.struts.MMainRepForm value object into a
	 * com.gather.hibernate.MMainRep object.
	 * 
	 * @param mMainRepPersistence
	 *            The com.gather.hibernate.MMainRep object into which the data
	 *            is to be copied.
	 * @param mMainRepForm
	 *            The com.gather.struts.MMainRepForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MMainRep mMainRepPersistence,
			com.gather.struts.forms.MMainRepForm mMainRepForm) throws Exception {
		// Persistence layer specific implementation
		MCurUnit mcur = new MCurUnit();
		MRepType mrep = new MRepType();
		mMainRepPersistence.setRepId(mMainRepForm.getRepId());
		mMainRepPersistence.setRepCnName(mMainRepForm.getRepCnName());
		mMainRepPersistence.setRepEnName(mMainRepForm.getRepEnName());
		/*
		 * mMainRepPersistence.getMCurUnit().setCurUnit(mMainRepForm.getCurUnit());
		 * mMainRepPersistence.getMRepType().setRepTypeId(mMainRepForm.getRepTypeId());
		 */
		mcur.setCurUnit(mMainRepForm.getCurUnit());
		mrep.setRepTypeId(mMainRepForm.getRepTypeId());
		mMainRepPersistence.setMCurUnit(mcur);
		mMainRepPersistence.setMRepType(mrep);
	}

	/**
	 * Copy data from a com.gather.hibernate.MMainRep object into a
	 * com.gather.struts.MMainRepForm value object.
	 * 
	 * @param mMainRepPersistence
	 *            The com.gather.hibernate.MMainRep object from which the data
	 *            is to be copied.
	 * @param mMainRepForm
	 *            The com.gather.struts.MMainRepForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MMainRep mMainRepPersistence,
			com.gather.struts.forms.MMainRepForm mMainRepForm) throws Exception {
		// Persistence layer specific implementation
		mMainRepForm.setRepId(mMainRepPersistence.getRepId());
		mMainRepForm.setRepCnName(mMainRepPersistence.getRepCnName());
		mMainRepForm.setRepEnName(mMainRepPersistence.getRepEnName());
		if (mMainRepPersistence.getMCurUnit() != null) {
			mMainRepForm.setCurUnit(mMainRepPersistence.getMCurUnit()
					.getCurUnit());
		}
		if (mMainRepPersistence.getMRepType() != null) {
			mMainRepForm.setRepTypeId(mMainRepPersistence.getMRepType()
					.getRepTypeId());
		}
	}

	/**
	 * Copy data from a com.gather.struts.ReportForm value object into a
	 * com.gather.hibernate.Report object.
	 * 
	 * @param reportPersistence
	 *            The com.gather.hibernate.Report object into which the data is
	 *            to be copied.
	 * @param reportForm
	 *            The com.gather.struts.ReportForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Report reportPersistence,
			com.gather.struts.forms.ReportForm reportForm) throws Exception {
	
		MChildReportPK mChildReportPK=new MChildReportPK();
		mChildReportPK.setVersionId(reportForm.getVersionId());
		MChildReport mChildReport=new MChildReport();
		mChildReport.setComp_id(mChildReportPK);
		reportPersistence.setMChildReport(mChildReport);
		reportPersistence.setRepId(reportForm.getRepId());

		MDataRgType mDataRgType=new MDataRgType();
		mDataRgType.setDataRangeId(reportForm.getDatarangeid());
		reportPersistence.setMDataRgType(mDataRgType);
		reportPersistence.setTerm(reportForm.getTerm());
		reportPersistence.setTimes(reportForm.getTimes());

		MOrg mOrg=new MOrg();
		mOrg.setOrgId(reportForm.getOrgid());
		reportPersistence.setMOrg(mOrg);
		
		reportPersistence.setTblOuterValidateFlag(reportForm
				.getTblOuterValidateFlag());
		reportPersistence.setReportDataWarehouseFlag(reportForm
				.getReportDataWarehouseFlag());
		reportPersistence.setRepRangeFlag(reportForm.getRepRangeFlag());
		reportPersistence.setAbmormityChangeFlag(reportForm
				.getAbmormityChangeFlag());
		reportPersistence.setTblInnerValidateFlag(reportForm
				.getTblInnerValidateFlag());
		reportPersistence.setRepName(reportForm.getRepName());
		reportPersistence.setCheckFlag(reportForm.getCheckFlag());
	
		mChildReportPK.setChildRepId(reportForm.getChildrepid());
		mChildReport.setComp_id(mChildReportPK);
		reportPersistence.setMChildReport(mChildReport);
		reportPersistence.setPNumber(reportForm.getPackage());
		reportPersistence.setReportFlag(reportForm.getReportFlag());
		reportPersistence.setFileFlag(reportForm.getFileFlag());
		reportPersistence.setLaterReportDay(reportForm.getLaterReportDay());
		reportPersistence.setWriter(reportForm.getWriter());

		 MCurr mCurr=new MCurr();
		 mCurr.setCurId(reportForm.getCurId());
		 reportPersistence.setMCurr( mCurr);
		reportPersistence.setReportDate(reportForm.getReportDate());
		reportPersistence.setNotReportFlag(reportForm.getNotReportFlag());
		reportPersistence.setChecker(reportForm.getChecker());
		reportPersistence.setPrincipal(reportForm.getPrincipal());
		reportPersistence.setYear(reportForm.getYear());
		reportPersistence.setFrequency(reportForm.getFrequency());
	}

	/**
	 * Copy data from a com.gather.hibernate.Report object into a
	 * com.gather.struts.ReportForm value object.
	 * 
	 * @param reportPersistence
	 *            The com.gather.hibernate.Report object from which the data is
	 *            to be copied.
	 * @param reportForm
	 *            The com.gather.struts.ReportForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Report reportPersistence,
			com.gather.struts.forms.ReportForm reportForm) throws Exception {
		// Persistence layer specific implementation
		if (reportPersistence.getMChildReport() != null) {
			reportForm.setVersionId(reportPersistence.getMChildReport()
					.getComp_id().getVersionId());
		}
		reportForm.setRepId(reportPersistence.getRepId());
		if (reportPersistence.getMDataRgType() != null) {
			reportForm.setDatarangeid(reportPersistence.getMDataRgType()
					.getDataRangeId());
		}
		reportForm.setTerm(reportPersistence.getTerm());
		reportForm.setTimes(reportPersistence.getTimes());
		if (reportPersistence.getMOrg() != null) {
			reportForm.setOrgid(reportPersistence.getMOrg().getOrgId());
		}
		reportForm.setTblOuterValidateFlag(reportPersistence
				.getTblOuterValidateFlag());
		reportForm.setReportDataWarehouseFlag(reportPersistence
				.getReportDataWarehouseFlag());
		reportForm.setRepRangeFlag(reportPersistence.getRepRangeFlag());
		reportForm.setAbmormityChangeFlag(reportPersistence
				.getAbmormityChangeFlag());
		reportForm.setTblInnerValidateFlag(reportPersistence
				.getTblInnerValidateFlag());
		reportForm.setRepName(reportPersistence.getRepName());
		reportForm.setCheckFlag(reportPersistence.getCheckFlag());
		if (reportPersistence.getMChildReport() != null) {
			reportForm.setChildrepid(reportPersistence.getMChildReport()
					.getComp_id().getChildRepId());
		}
		reportForm.setPackage(reportPersistence.getPNumber());
		reportForm.setReportFlag(reportPersistence.getReportFlag());
		reportForm.setFileFlag(reportPersistence.getFileFlag());
		reportForm.setLaterReportDay(reportPersistence.getLaterReportDay());
		reportForm.setWriter(reportPersistence.getWriter());
		if (reportPersistence.getMCurr() != null) {
			reportForm.setCurId(reportPersistence.getMCurr().getCurId());
		}
		reportForm.setReportDate(reportPersistence.getReportDate());
		reportForm.setNotReportFlag(reportPersistence.getNotReportFlag());
		reportForm.setChecker(reportPersistence.getChecker());
		reportForm.setPrincipal(reportPersistence.getPrincipal());
		reportForm.setYear(reportPersistence.getYear());
		reportForm.setFrequency(reportPersistence.getFrequency());

	}

	/**
	 * 
	 * 姬怀宝 新增的方法
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Report reportPersistence,
			com.gather.struts.forms.CopyReportform reportForm) throws Exception {
		// Persistence layer specific implementation
		if (reportPersistence.getMChildReport() != null) {
			reportForm.setVersionId(reportPersistence.getMChildReport()
					.getComp_id().getVersionId());
		}
		reportForm.setRepId(reportPersistence.getRepId());
		if (reportPersistence.getMDataRgType() != null) {
			reportForm.setDatarangeid(reportPersistence.getMDataRgType()
					.getDataRangeId());
		}
		reportForm.setTerm(reportPersistence.getTerm());
		reportForm.setTimes(reportPersistence.getTimes());
		if (reportPersistence.getMOrg() != null) {
			reportForm.setOrgid(reportPersistence.getMOrg().getOrgId());
		}
		reportForm.setTblOuterValidateFlag(reportPersistence
				.getTblOuterValidateFlag());
		reportForm.setReportDataWarehouseFlag(reportPersistence
				.getReportDataWarehouseFlag());
		reportForm.setRepRangeFlag(reportPersistence.getRepRangeFlag());
		reportForm.setAbmormityChangeFlag(reportPersistence
				.getAbmormityChangeFlag());
		reportForm.setTblInnerValidateFlag(reportPersistence
				.getTblInnerValidateFlag());
		reportForm.setRepName(reportPersistence.getRepName());
		reportForm.setCheckFlag(reportPersistence.getCheckFlag());
		if (reportPersistence.getMChildReport() != null) {
			reportForm.setChildrepid(reportPersistence.getMChildReport()
					.getComp_id().getChildRepId());
		}
		reportForm.setPackage(reportPersistence.getPNumber());
		reportForm.setReportFlag(reportPersistence.getReportFlag());
		reportForm.setFileFlag(reportPersistence.getFileFlag());
		reportForm.setLaterReportDay(reportPersistence.getLaterReportDay());
		reportForm.setWriter(reportPersistence.getWriter());
		if (reportPersistence.getMCurr() != null) {
			reportForm.setCurId(reportPersistence.getMCurr().getCurId());
		}
		reportForm.setReportDate(reportPersistence.getReportDate());
		reportForm.setNotReportFlag(reportPersistence.getNotReportFlag());
		reportForm.setChecker(reportPersistence.getChecker());
		reportForm.setPrincipal(reportPersistence.getPrincipal());
		reportForm.setYear(reportPersistence.getYear());
		reportForm.setFrequency(reportPersistence.getFrequency());

	}

	/**
	 * Copy data from a com.gather.struts.MRepTypeForm value object into a
	 * com.gather.hibernate.MRepType object.
	 * 
	 * @param mRepTypePersistence
	 *            The com.gather.hibernate.MRepType object into which the data
	 *            is to be copied.
	 * @param mRepTypeForm
	 *            The com.gather.struts.MRepTypeForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MRepType mRepTypePersistence,
			com.gather.struts.forms.MRepTypeForm mRepTypeForm) throws Exception {
		// Persistence layer specific implementation
		mRepTypePersistence.setRepTypeId(mRepTypeForm.getRepTypeId());
		mRepTypePersistence.setRepTypeName(mRepTypeForm.getRepTypeName());
	}

	/**
	 * Copy data from a com.gather.hibernate.MRepType object into a
	 * com.gather.struts.MRepTypeForm value object.
	 * 
	 * @param mRepTypePersistence
	 *            The com.gather.hibernate.MRepType object from which the data
	 *            is to be copied.
	 * @param mRepTypeForm
	 *            The com.gather.struts.MRepTypeForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MRepType mRepTypePersistence,
			com.gather.struts.forms.MRepTypeForm mRepTypeForm) throws Exception {
		// Persistence layer specific implementation
		mRepTypeForm.setRepTypeId(mRepTypePersistence.getRepTypeId());
		mRepTypeForm.setRepTypeName(mRepTypePersistence.getRepTypeName());
	}

	/**
	 * Copy data from a com.gather.struts.ResourceTypeForm value object into a
	 * com.gather.hibernate.ResourceType object.
	 * 
	 * @param resourceTypePersistence
	 *            The com.gather.hibernate.ResourceType object into which the
	 *            data is to be copied.
	 * @param resourceTypeForm
	 *            The com.gather.struts.ResourceTypeForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.ResourceType resourceTypePersistence,
			com.gather.struts.forms.ResourceTypeForm resourceTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		resourceTypePersistence.setResourceTypeId(resourceTypeForm
				.getResourceTypeId());
		resourceTypePersistence.setTypeName(resourceTypeForm.getTypeName());
	}

	/**
	 * Copy data from a com.gather.hibernate.ResourceType object into a
	 * com.gather.struts.ResourceTypeForm value object.
	 * 
	 * @param resourceTypePersistence
	 *            The com.gather.hibernate.ResourceType object from which the
	 *            data is to be copied.
	 * @param resourceTypeForm
	 *            The com.gather.struts.ResourceTypeForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.ResourceType resourceTypePersistence,
			com.gather.struts.forms.ResourceTypeForm resourceTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		resourceTypeForm.setResourceTypeId(resourceTypePersistence
				.getResourceTypeId());
		resourceTypeForm.setTypeName(resourceTypePersistence.getTypeName());
	}

	/**
	 * Copy data from a com.gather.struts.ClientForm value object into a
	 * com.gather.hibernate.Client object.
	 * 
	 * @param clientPersistence
	 *            The com.gather.hibernate.Client object into which the data is
	 *            to be copied.
	 * @param clientForm
	 *            The com.gather.struts.ClientForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Client clientPersistence,
			com.gather.struts.forms.ClientForm clientForm) throws Exception {
		// Persistence layer specific implementation
		clientPersistence.setId(clientForm.getId());
		clientPersistence.setClientVersion(clientForm.getClientVersion());
		clientPersistence.setClientSize(clientForm.getClientSize());
		clientPersistence.setNote(clientForm.getNote());
		clientPersistence.setClientEntity(clientForm.getClientEntity());
		clientPersistence.setDownTime(clientForm.getDownTime());
	}

	/**
	 * Copy data from a com.gather.hibernate.Client object into a
	 * com.gather.struts.ClientForm value object.
	 * 
	 * @param clientPersistence
	 *            The com.gather.hibernate.Client object from which the data is
	 *            to be copied.
	 * @param clientForm
	 *            The com.gather.struts.ClientForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Client clientPersistence,
			com.gather.struts.forms.ClientForm clientForm) throws Exception {
		// Persistence layer specific implementation
		clientForm.setId(clientPersistence.getId());
		clientForm.setClientVersion(clientPersistence.getClientVersion());
		clientForm.setClientSize(clientPersistence.getClientSize());
		clientForm.setNote(clientPersistence.getNote());
		clientForm.setClientEntity(clientPersistence.getClientEntity());
		clientForm.setDownTime(clientPersistence.getDownTime());
	}

	/**
	 * Copy data from a com.gather.struts.ValidateTypeForm value object into a
	 * com.gather.hibernate.ValidateType object.
	 * 
	 * @param validateTypePersistence
	 *            The com.gather.hibernate.ValidateType object into which the
	 *            data is to be copied.
	 * @param validateTypeForm
	 *            The com.gather.struts.ValidateTypeForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.ValidateType validateTypePersistence,
			com.gather.struts.forms.ValidateTypeForm validateTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		validateTypePersistence.setValidateTypeId(validateTypeForm.getValidateTypeId());
		validateTypePersistence.setValidateTypeName(validateTypeForm.getValidateTypeName());
	}

	/**
	 * Copy data from a com.gather.hibernate.ValidateType object into a
	 * com.gather.struts.ValidateTypeForm value object.
	 * 
	 * @param validateTypePersistence
	 *            The com.gather.hibernate.ValidateType object from which the
	 *            data is to be copied.
	 * @param validateTypeForm
	 *            The com.gather.struts.ValidateTypeForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.ValidateType validateTypePersistence,
			com.gather.struts.forms.ValidateTypeForm validateTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		validateTypeForm.setValidateTypeId(validateTypePersistence
				.getValidateTypeId());
		validateTypeForm.setValidateTypeName(validateTypePersistence
				.getValidateTypeName());
	}

	/**
	 * Copy data from a com.gather.struts.MDataRgTypeForm value object into a
	 * com.gather.hibernate.MDataRgType object.
	 * 
	 * @param mDataRgTypePersistence
	 *            The com.gather.hibernate.MDataRgType object into which the
	 *            data is to be copied.
	 * @param mDataRgTypeForm
	 *            The com.gather.struts.MDataRgTypeForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MDataRgType mDataRgTypePersistence,
			com.gather.struts.forms.MDataRgTypeForm mDataRgTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		mDataRgTypePersistence.setDataRangeId(mDataRgTypeForm.getDataRangeId());
		mDataRgTypePersistence.setDataRgDesc(mDataRgTypeForm.getDataRgDesc());
	}

	/**
	 * Copy data from a com.gather.hibernate.MDataRgType object into a
	 * com.gather.struts.MDataRgTypeForm value object.
	 * 
	 * @param mDataRgTypePersistence
	 *            The com.gather.hibernate.MDataRgType object from which the
	 *            data is to be copied.
	 * @param mDataRgTypeForm
	 *            The com.gather.struts.MDataRgTypeForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MDataRgType mDataRgTypePersistence,
			com.gather.struts.forms.MDataRgTypeForm mDataRgTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		mDataRgTypeForm.setDataRangeId(mDataRgTypePersistence.getDataRangeId());
		mDataRgTypeForm.setDataRgDesc(mDataRgTypePersistence.getDataRgDesc());
	}

	/**
	 * Copy data from a com.gather.struts.DataValidateInfoForm value object into
	 * a com.gather.hibernate.DataValidateInfo object.
	 * 
	 * @param dataValidateInfoPersistence
	 *            The com.gather.hibernate.DataValidateInfo object into which
	 *            the data is to be copied.
	 * @param dataValidateInfoForm
	 *            The com.gather.struts.DataValidateInfoForm value object
	 *            containing the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.DataValidateInfo dataValidateInfoPersistence,
			com.gather.struts.forms.DataValidateInfoForm dataValidateInfoForm)
			throws Exception {
		// System.out.println(dataValidateInfoForm.getCellFormId());
		// System.out.println(dataValidateInfoForm.getRepOutId());
		// System.out.println(dataValidateInfoForm.getValidateTypeId());
		DataValidateInfoPK dataValidateInfoPK=new DataValidateInfoPK();
		dataValidateInfoPK.setRepOutId(dataValidateInfoForm.getRepOutId());
		dataValidateInfoPK.setSequenceId(dataValidateInfoForm.getSequenceId());
		dataValidateInfoPersistence.setComp_id(dataValidateInfoPK);
		/* ValidateType  validateType=new  ValidateType();
		 validateType.setValidateTypeId(dataValidateInfoForm.getValidateTypeId());*/
		 dataValidateInfoPersistence.setValidateTypeId(dataValidateInfoForm.getValidateTypeId());
		/* MCellForm mCellForm=new MCellForm();
		 mCellForm.setCellFormId(dataValidateInfoForm.getCellFormId());*/
		 dataValidateInfoPersistence.setCellFormId(dataValidateInfoForm.getCellFormId());
	
	}

	/**
	 * Copy data from a com.gather.hibernate.DataValidateInfo object into a
	 * com.gather.struts.DataValidateInfoForm value object.
	 * 
	 * @param dataValidateInfoPersistence
	 *            The com.gather.hibernate.DataValidateInfo object from which
	 *            the data is to be copied.
	 * @param dataValidateInfoForm
	 *            The com.gather.struts.DataValidateInfoForm value object into
	 *            which the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.DataValidateInfo dataValidateInfoPersistence,
			com.gather.struts.forms.DataValidateInfoForm dataValidateInfoForm)
			throws Exception {
		// Persistence layer specific implementation
		dataValidateInfoForm.setRepOutId(dataValidateInfoPersistence
				.getComp_id().getRepOutId());
		if (dataValidateInfoPersistence.getValidateType() != null) {
			dataValidateInfoForm.setValidateTypeId(dataValidateInfoPersistence
					.getValidateType().getValidateTypeId());
		}
		if (dataValidateInfoPersistence.getMCellForm() != null) {
			dataValidateInfoForm.setCellFormId(dataValidateInfoPersistence
					.getMCellForm().getCellFormId());
		}
	}

	/**
	 * 姬怀宝 新增的查找方法
	 * 
	 * 
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.DataValidateInfo dataValidateInfoPersistence,
			com.gather.struts.forms.Report_errorform report_errorform)
			throws Exception {
		if (dataValidateInfoPersistence.getValidateType() != null) {
			report_errorform.setValidateTypeName(dataValidateInfoPersistence
					.getValidateType().getValidateTypeName());
		}
		if (dataValidateInfoPersistence.getMCellForm() != null) {
			report_errorform.setCellForm(dataValidateInfoPersistence
					.getMCellForm().getCellForm());
		}
	}

	/**
	 * Copy data from a com.gather.struts.DownloadResourceForm value object into
	 * a com.gather.hibernate.DownloadResource object.
	 * 
	 * @param downloadResourcePersistence
	 *            The com.gather.hibernate.DownloadResource object into which
	 *            the data is to be copied.
	 * @param downloadResourceForm
	 *            The com.gather.struts.DownloadResourceForm value object
	 *            containing the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.DownloadResource downloadResourcePersistence,
			com.gather.struts.forms.DownloadResourceForm downloadResourceForm)
			throws Exception {
		// Persistence layer specific implementation
		downloadResourcePersistence.setResourceId(downloadResourceForm
				.getResourceId());
		if (downloadResourcePersistence.getResourceType() != null) {
			downloadResourcePersistence.getResourceType().setResourceTypeId(
					downloadResourceForm.getResourceTypeId());
		}
		downloadResourcePersistence.setResourceName(downloadResourceForm
				.getResourceName());
		downloadResourcePersistence.setUpdateTime(downloadResourceForm
				.getUpdateTime());
		downloadResourcePersistence.setDownTimes(downloadResourceForm
				.getDownTimes());
		downloadResourcePersistence.setFileSize(downloadResourceForm
				.getFileSize());
	}

	/**
	 * Copy data from a com.gather.hibernate.DownloadResource object into a
	 * com.gather.struts.DownloadResourceForm value object.
	 * 
	 * @param downloadResourcePersistence
	 *            The com.gather.hibernate.DownloadResource object from which
	 *            the data is to be copied.
	 * @param downloadResourceForm
	 *            The com.gather.struts.DownloadResourceForm value object into
	 *            which the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.DownloadResource downloadResourcePersistence,
			com.gather.struts.forms.DownloadResourceForm downloadResourceForm)
			throws Exception {
		// Persistence layer specific implementation
		downloadResourceForm.setResourceId(downloadResourcePersistence
				.getResourceId());
		if (downloadResourcePersistence.getResourceType() != null) {
			downloadResourceForm.setResourceTypeId(downloadResourcePersistence
					.getResourceType().getResourceTypeId());
		}
		downloadResourceForm.setResourceName(downloadResourcePersistence
				.getResourceName());
		downloadResourceForm.setUpdateTime(downloadResourcePersistence
				.getUpdateTime());
		downloadResourceForm.setDownTimes(downloadResourcePersistence
				.getDownTimes());
		downloadResourceForm.setFileSize(downloadResourcePersistence
				.getFileSize());
	}

	/**
	 * @author linfeng
	 * 
	 * @param mChildReportPersistence
	 *            The com.gather.hibernate.MChildReport object into which the
	 *            data is to be copied.
	 * @param RealReportForm
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MChildReport mChildReportPersistence,
			RealReportForm mChildReportForm) throws Exception {
		// Persistence layer specific implementation
		mChildReportPersistence.getComp_id().setChildRepId(
				mChildReportForm.getChildRepId());
		mChildReportPersistence.getComp_id().setVersionId(
				mChildReportForm.getVersionId());
		mChildReportPersistence.setReportName(mChildReportForm.getReportName());
		mChildReportPersistence.setStartDate(mChildReportForm.getStartDate());
		mChildReportPersistence.setEndDate(mChildReportForm.getEndDate());
		mChildReportPersistence.setFormatTempId(mChildReportForm
				.getFormatTempId());
		if (mChildReportPersistence.getMMainRep() != null) {
			mChildReportPersistence.getMMainRep().setRepId(
					mChildReportForm.getRepId());
		}
		if (mChildReportPersistence.getMCurUnit() != null) {
			mChildReportPersistence.getMCurUnit().setCurUnit(
					mChildReportForm.getCurUnit());
		}
	}

	/**
	 * @author linfeng
	 * 
	 * @param mChildReportPersistence
	 *            The com.gather.hibernate.MChildReport object into which the
	 *            data is to be copied.
	 * @param RealReportForm
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MChildReport mChildReportPersistence,
			RealReportForm realReportForm) throws Exception {
		// Persistence layer specific implementation
		realReportForm.setChildRepId(mChildReportPersistence.getComp_id()
				.getChildRepId());
		System.out
				.println("copyPersistenceToVo::realReportForm.setChildRepId is:"
						+ realReportForm.getChildRepId());
		realReportForm.setVersionId(mChildReportPersistence.getComp_id()
				.getVersionId());
		realReportForm.setReportName(mChildReportPersistence.getReportName());
		realReportForm.setStartDate(mChildReportPersistence.getStartDate());
		realReportForm.setEndDate(mChildReportPersistence.getEndDate());
		realReportForm.setFormatTempId(mChildReportPersistence
				.getFormatTempId());
		if (mChildReportPersistence.getMMainRep() != null) {
			realReportForm.setRepId(mChildReportPersistence.getMMainRep()
					.getRepId());
		}
		if (mChildReportPersistence.getMCurUnit() != null) {
			realReportForm.setCurUnit(mChildReportPersistence.getMCurUnit()
					.getCurUnit());
		}
		realReportForm.setMActuReps(mChildReportPersistence.getMActuReps());
		realReportForm.setMRepRanges(mChildReportPersistence.getMRepRanges());
		realReportForm.setReports(mChildReportPersistence.getMRepRanges());
		realReportForm.setRepRangeDownLogs(mChildReportPersistence
				.getMRepRanges());

		// realReportForm.getChild_repId();
		// realReportForm.getDataRangeId(mChildReportPersistence.getMRepRanges());
	}

	public static void copyVoToVo(RealReportForm realReportFormSource,
			RealReportForm realReportFormTo) {
		realReportFormTo.setChild_curUnit(realReportFormSource
				.getChild_curUnit());
		realReportFormTo.setChild_repId(realReportFormSource.getChild_repId());
		realReportFormTo.setCurUnit(realReportFormSource.getCurUnit());
		realReportFormTo.setDataRangeId(realReportFormSource.getDataRangeId());
		realReportFormTo.setDataRangeName(realReportFormSource
				.getDataRangeName());
		realReportFormTo.setDelayTime(realReportFormSource.getDelayTime());
		realReportFormTo.setEndDate(realReportFormSource.getEndDate());
		realReportFormTo
				.setFormatTempId(realReportFormSource.getFormatTempId());
		realReportFormTo.setNormalTime(realReportFormSource.getNormalTime());
		realReportFormTo.setRealChildRepId(realReportFormSource
				.getRealChildRepId());
		realReportFormTo.setRealVersionId(realReportFormSource
				.getRealVersionId());
		realReportFormTo.setRepCnName(realReportFormSource.getRepCnName());
		realReportFormTo.setRepEnName(realReportFormSource.getRepEnName());
		realReportFormTo.setRepFreqId(realReportFormSource.getRepFreqId());
		realReportFormTo.setRepFreqName(realReportFormSource.getRepFreqName());
		realReportFormTo.setRepId(realReportFormSource.getRepId());
		realReportFormTo.setReportName(realReportFormSource.getReportName());
		realReportFormTo.setRepTypeId(realReportFormSource.getRepTypeId());
		realReportFormTo.setRepTypeName(realReportFormSource.getRepTypeName());
		realReportFormTo.setVersionId(realReportFormSource.getVersionId());
		realReportFormTo.setStartDate(realReportFormSource.getStartDate());
		realReportFormTo.setChildRepId(realReportFormSource.getChildRepId());
		realReportFormTo.setOrgId(realReportFormSource.getOrgId());
		realReportFormTo.setOrgName(realReportFormSource.getOrgName());
		realReportFormTo.setYear(realReportFormSource.getYear());
		realReportFormTo.setMonth(realReportFormSource.getMonth());

	}

	/**
	 * Copy data from a com.gather.struts.MChildReportForm value object into a
	 * com.gather.hibernate.MChildReport object.
	 * 
	 * @param mChildReportPersistence
	 *            The com.gather.hibernate.MChildReport object into which the
	 *            data is to be copied.
	 * @param mChildReportForm
	 *            The com.gather.struts.MChildReportForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MChildReport mChildReportPersistence,
			com.gather.struts.forms.MChildReportForm mChildReportForm)
			throws Exception {
		MChildReportPK pk1 = new MChildReportPK();
		pk1.setChildRepId(mChildReportForm.getChildRepId());
		pk1.setVersionId(mChildReportForm.getVersionId());
		mChildReportPersistence.setComp_id(pk1);
		
		if(mChildReportForm.getRepId()!=null){
			MMainRep mmainrep = new MMainRep();
			mmainrep.setRepId(mChildReportForm.getRepId());
			mChildReportPersistence.setMMainRep(mmainrep);
		}
		
		if(mChildReportForm.getCurUnit()!=null){
			MCurUnit mcurunit = new MCurUnit();
			mcurunit.setCurUnit(mChildReportForm.getCurUnit());
			mChildReportPersistence.setMCurUnit(mcurunit);
		}
		
		if(mChildReportForm.getReportName()!=null) mChildReportPersistence.setReportName(mChildReportForm.getReportName());
		if(mChildReportForm.getStartDate()!=null) mChildReportPersistence.setStartDate(mChildReportForm.getStartDate());
		if(mChildReportForm.getEndDate()!=null) mChildReportPersistence.setEndDate(mChildReportForm.getEndDate());
		if(mChildReportForm.getFormatTempId()!=null) mChildReportPersistence.setFormatTempId(mChildReportForm.getFormatTempId());
	}

	/**
	 * Copy data from a com.gather.hibernate.MChildReport object into a
	 * com.gather.struts.MChildReportForm value object.
	 * 
	 * @param mChildReportPersistence
	 *            The com.gather.hibernate.MChildReport object from which the
	 *            data is to be copied.
	 * @param mChildReportForm
	 *            The com.gather.struts.MChildReportForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MChildReport mChildReportPersistence,
			com.gather.struts.forms.MChildReportForm mChildReportForm)
			throws Exception {
		// Persistence layer specific implementation
		mChildReportForm.setChildRepId(mChildReportPersistence.getComp_id()
				.getChildRepId());
		mChildReportForm.setVersionId(mChildReportPersistence.getComp_id()
				.getVersionId());
		mChildReportForm.setReportName(mChildReportPersistence.getReportName());
		mChildReportForm.setStartDate(mChildReportPersistence.getStartDate());
		mChildReportForm.setEndDate(mChildReportPersistence.getEndDate());
		mChildReportForm.setFormatTempId(mChildReportPersistence
				.getFormatTempId());
		if (mChildReportPersistence.getMMainRep() != null) {
			mChildReportForm.setRepId(mChildReportPersistence.getMMainRep()
					.getRepId());
		}
		if (mChildReportPersistence.getMCurUnit() != null) {
			mChildReportForm.setCurUnit(mChildReportPersistence.getMCurUnit()
					.getCurUnit());
		}
	}

	/**
	 * Copy data from a com.gather.struts.MOrgForm value object into a
	 * com.gather.hibernate.MOrg object.
	 * 
	 * @param mOrgPersistence
	 *            The com.gather.hibernate.MOrg object into which the data is to
	 *            be copied.
	 * @param mOrgForm
	 *            The com.gather.struts.MOrgForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MOrg mOrgPersistence,
			com.gather.struts.forms.MOrgForm mOrgForm) throws Exception {
		// Persistence layer specific implementation
		if(mOrgPersistence.getOrgId()==null) mOrgPersistence.setOrgId(mOrgForm.getOrgId());
		if(mOrgForm.getOrgName()!=null) mOrgPersistence.setOrgName(mOrgForm.getOrgName());
		if(mOrgForm.getOrgType()!=null) mOrgPersistence.setOrgType(mOrgForm.getOrgType());
		if(mOrgForm.getIsCorp()!=null) mOrgPersistence.setIsCorp(mOrgForm.getIsCorp());
		if(mOrgForm.getIsInUsing()!=null) mOrgPersistence.setIsInUsing(mOrgForm.getIsInUsing());
	}

	/**
	 * Copy data from a com.gather.hibernate.MOrg object into a
	 * com.gather.struts.MOrgForm value object.
	 * 
	 * @param mOrgPersistence
	 *            The com.gather.hibernate.MOrg object from which the data is to
	 *            be copied.
	 * @param mOrgForm
	 *            The com.gather.struts.MOrgForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MOrg mOrgPersistence,
			com.gather.struts.forms.MOrgForm mOrgForm) throws Exception {
		// Persistence layer specific implementation
		mOrgForm.setOrgId(mOrgPersistence.getOrgId());
		mOrgForm.setOrgName(mOrgPersistence.getOrgName());
		mOrgForm.setOrgType(mOrgPersistence.getOrgType());
		mOrgForm.setIsCorp(mOrgPersistence.getIsCorp());
		mOrgForm.setIsInUsing(mOrgPersistence.getIsInUsing());
	}

	/**
	 * Copy data from a com.gather.struts.MActuRepForm value object into a
	 * com.gather.hibernate.MActuRep object.
	 * 
	 * @param mActuRepPersistence
	 *            The com.gather.hibernate.MActuRep object into which the data
	 *            is to be copied.
	 * @param mActuRepForm
	 *            The com.gather.struts.MActuRepForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MActuRep mActuRepPersistence,
			com.gather.struts.forms.MActuRepForm mActuRepForm) throws Exception {
		MActuRepPK mActuRepPK = new MActuRepPK();
		mActuRepPK.setVersionId(mActuRepForm.getVersionId());
		mActuRepPK.setChildRepId(mActuRepForm.getChildRepId());
		mActuRepPK.setRepFreqId(mActuRepForm.getRepFreqId());
		mActuRepPK.setDataRangeId(mActuRepForm.getDataRangeId());
		mActuRepPK.setOrgType(mActuRepForm.getOrgType());
		mActuRepPersistence.setComp_id(mActuRepPK);
		/*// System.out.println("vvv"+mActuRepPK.getVersionId());
		// System.out.println("ccc"+mActuRepPK.getChildRepId());*/
		mActuRepPersistence.setDelayTime(mActuRepForm.getDelayTime());
		mActuRepPersistence.setNormalTime(mActuRepForm.getNormalTime());
	}

	/**
	 * Copy data from a com.gather.hibernate.MActuRep object into a
	 * com.gather.struts.MActuRepForm value object.
	 * 
	 * @param mActuRepPersistence
	 *            The com.gather.hibernate.MActuRep object from which the data
	 *            is to be copied.
	 * @param mActuRepForm
	 *            The com.gather.struts.MActuRepForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MActuRep mActuRepPersistence,
			com.gather.struts.forms.MActuRepForm mActuRepForm) throws Exception {
		// Persistence layer specific implementation
		mActuRepForm.setVersionId(mActuRepPersistence.getComp_id()
				.getVersionId());
		mActuRepForm.setDelayTime(mActuRepPersistence.getDelayTime());
		if (mActuRepPersistence.getMRepFreq() != null) {
			mActuRepForm.setRepFreqId(mActuRepPersistence.getMRepFreq()
					.getRepFreqId());
		}
		if (mActuRepPersistence.getMDataRgType() != null) {
			mActuRepForm.setDataRangeId(mActuRepPersistence.getMDataRgType()
					.getDataRangeId());
		}
		mActuRepForm.setChildRepId(mActuRepPersistence.getComp_id()
				.getChildRepId());
		mActuRepForm.setNormalTime(mActuRepPersistence.getNormalTime());
	}

	/**
	 * Copy data from a com.gather.struts.MRepFreqForm value object into a
	 * com.gather.hibernate.MRepFreq object.
	 * 
	 * @param mRepFreqPersistence
	 *            The com.gather.hibernate.MRepFreq object into which the data
	 *            is to be copied.
	 * @param mRepFreqForm
	 *            The com.gather.struts.MRepFreqForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MRepFreq mRepFreqPersistence,
			com.gather.struts.forms.MRepFreqForm mRepFreqForm) throws Exception {
		// Persistence layer specific implementation
		mRepFreqPersistence.setRepFreqId(mRepFreqForm.getRepFreqId());
		mRepFreqPersistence.setRepFreqName(mRepFreqForm.getRepFreqName());
	}

	/**
	 * Copy data from a com.gather.hibernate.MRepFreq object into a
	 * com.gather.struts.MRepFreqForm value object.
	 * 
	 * @param mRepFreqPersistence
	 *            The com.gather.hibernate.MRepFreq object from which the data
	 *            is to be copied.
	 * @param mRepFreqForm
	 *            The com.gather.struts.MRepFreqForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MRepFreq mRepFreqPersistence,
			com.gather.struts.forms.MRepFreqForm mRepFreqForm) throws Exception {
		// Persistence layer specific implementation
		mRepFreqForm.setRepFreqId(mRepFreqPersistence.getRepFreqId());
		mRepFreqForm.setRepFreqName(mRepFreqPersistence.getRepFreqName());
	}

	/**
	 * Copy data from a com.gather.struts.CalendarForm value object into a
	 * com.gather.hibernate.Calendar object.
	 * 
	 * @param calendarPersistence
	 *            The com.gather.hibernate.Calendar object into which the data
	 *            is to be copied.
	 * @param calendarForm
	 *            The com.gather.struts.CalendarForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Calendar calendarPersistence,
			com.gather.struts.forms.CalendarForm calendarForm) throws Exception {
		// Persistence layer specific implementation
		calendarPersistence.setCalId(calendarForm.getCalId());
		calendarPersistence.setCalName(calendarForm.getCalName());
		calendarPersistence.setCalMethod(calendarForm.getCalMethod());
	}

	/**
	 * Copy data from a com.gather.hibernate.Calendar object into a
	 * com.gather.struts.CalendarForm value object.
	 * 
	 * @param calendarPersistence
	 *            The com.gather.hibernate.Calendar object from which the data
	 *            is to be copied.
	 * @param calendarForm
	 *            The com.gather.struts.CalendarForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Calendar calendarPersistence,
			com.gather.struts.forms.CalendarForm calendarForm) throws Exception {
		// Persistence layer specific implementation
		calendarForm.setCalId(calendarPersistence.getCalId());
		calendarForm.setCalName(calendarPersistence.getCalName());
		calendarForm.setCalMethod(calendarPersistence.getCalMethod());
	}

	/**
	 * Copy data from a com.gather.struts.MCurrForm value object into a
	 * com.gather.hibernate.MCurr object.
	 * 
	 * @param mCurrPersistence
	 *            The com.gather.hibernate.MCurr object into which the data is
	 *            to be copied.
	 * @param mCurrForm
	 *            The com.gather.struts.MCurrForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MCurr mCurrPersistence,
			com.gather.struts.forms.MCurrForm mCurrForm) throws Exception {
		// Persistence layer specific implementation
		mCurrPersistence.setCurId(mCurrForm.getCurId());
		mCurrPersistence.setCurName(mCurrForm.getCurName());
	}

	/**
	 * Copy data from a com.gather.hibernate.MCurr object into a
	 * com.gather.struts.MCurrForm value object.
	 * 
	 * @param mCurrPersistence
	 *            The com.gather.hibernate.MCurr object from which the data is
	 *            to be copied.
	 * @param mCurrForm
	 *            The com.gather.struts.MCurrForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MCurr mCurrPersistence,
			com.gather.struts.forms.MCurrForm mCurrForm) throws Exception {
		// Persistence layer specific implementation
		mCurrForm.setCurId(mCurrPersistence.getCurId());
		mCurrForm.setCurName(mCurrPersistence.getCurName());
	}

	/**
	 * Copy data from a com.gather.struts.LogForm value object into a
	 * com.gather.hibernate.Log object.
	 * 
	 * @param logPersistence
	 *            The com.gather.hibernate.Log object into which the data is to
	 *            be copied.
	 * @param logForm
	 *            The com.gather.struts.LogForm value object containing the data
	 *            to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Log logPersistence,
			com.gather.struts.forms.LogForm logForm) throws Exception {
		// Persistence layer specific implementation
		logPersistence.setLogId(logForm.getLogId());
		logPersistence.setUserName(logForm.getUserName());
		logPersistence.setLogTime(logForm.getLogTime());
		logPersistence.setOperation(logForm.getOperation());
		logPersistence.setMemo(logForm.getMemo());
		if (logPersistence.getLogType() != null) {
			logPersistence.getLogType().setLogTypeId(logForm.getLogTypeId());
		}

	}

	/*
	 * 新增加的删除方法
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Log logPersistence,
			com.gather.struts.forms.CopyLogform copyLogform) throws Exception {
		// Persistence layer specific implementation
		logPersistence.setLogId(copyLogform.getLogId());
		// logPersistence.setUserName(copyLogform.getUserName());
		// logPersistence.setLogTime(copyLogform.getLogTime());
		logPersistence.setOperation(copyLogform.getOperation());
		// logPersistence.setMemo(copyLogform.getMemo());
		// logPersistence.setLogType(null).setLogTypeId(copyLogform.getLogTypeId());

		/*
		 * logInPersistence.setLogInId(logInForm.getLogInId());
		 * logInPersistence.setUserName(logInForm.getUserName());
		 * logInPersistence.setLogTime(logInForm.getLogTimeAsDate());
		 * logInPersistence.setOperation(logInForm.getOperation());
		 * logInPersistence.setMemo(logInForm.getMemo());
		 * logInPersistence.setLogTypeId(logInForm.getLogTypeId());
		 */
	}

	/**
	 * Copy data from a com.gather.hibernate.Log object into a
	 * com.gather.struts.LogForm value object.
	 * 
	 * @param logPersistence
	 *            The com.gather.hibernate.Log object from which the data is to
	 *            be copied.
	 * @param logForm
	 *            The com.gather.struts.LogForm value object into which the data
	 *            is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Log logPersistence,
			com.gather.struts.forms.LogForm logForm) throws Exception {
		// Persistence layer specific implementation
		logForm.setLogId(logPersistence.getLogId());
		logForm.setUserName(logPersistence.getUserName());
		logForm.setLogTime(logPersistence.getLogTime());
		logForm.setOperation(logPersistence.getOperation());
		logForm.setMemo(logPersistence.getMemo());
		logForm.setOrgId(logPersistence.getOrgId());
		if (logPersistence.getLogType() != null) {
			logForm.setLogTypeId(logPersistence.getLogType().getLogTypeId());
		}
	}

	/**
	 * Copy data from a com.gather.struts.MRepRangeForm value object into a
	 * com.gather.hibernate.MRepRange object.
	 * 
	 * @param mRepRangePersistence
	 *            The com.gather.hibernate.MRepRange object into which the data
	 *            is to be copied.
	 * @param mRepRangeForm
	 *            The com.gather.struts.MRepRangeForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MRepRange mRepRangePersistence,
			com.gather.struts.forms.MRepRangeForm mRepRangeForm)
			throws Exception {
		// Persistence layer specific implementation
		// mRepRangePersistence.getComp_id().setChildRepId(mRepRangeForm.getChildRepId());
		// mRepRangePersistence.getComp_id().setOrgId(mRepRangeForm.getOrgId());
		// mRepRangePersistence.getComp_id().setVersionId(mRepRangeForm.getVersionId());
		MRepRangePK pk = new MRepRangePK();
		pk.setChildRepId(mRepRangeForm.getChildRepId());
		pk.setOrgId(mRepRangeForm.getOrgId());
		pk.setVersionId(mRepRangeForm.getVersionId());
		mRepRangePersistence.setComp_id(pk);
	}

	/**
	 * Copy data from a com.gather.hibernate.MRepRange object into a
	 * com.gather.struts.MRepRangeForm value object.
	 * 
	 * @param mRepRangePersistence
	 *            The com.gather.hibernate.MRepRange object from which the data
	 *            is to be copied.
	 * @param mRepRangeForm
	 *            The com.gather.struts.MRepRangeForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MRepRange mRepRangePersistence,
			com.gather.struts.forms.MRepRangeForm mRepRangeForm)
			throws Exception {
		// Persistence layer specific implementation
		mRepRangeForm.setChildRepId(mRepRangePersistence.getComp_id()
				.getChildRepId());
		mRepRangeForm.setOrgId(mRepRangePersistence.getComp_id().getOrgId());
		mRepRangeForm.setVersionId(mRepRangePersistence.getComp_id()
				.getVersionId());
	}

	/**
	 * Copy data from a com.gather.struts.LogTypeForm value object into a
	 * com.gather.hibernate.LogType object.
	 * 
	 * @param logTypePersistence
	 *            The com.gather.hibernate.LogType object into which the data is
	 *            to be copied.
	 * @param logTypeForm
	 *            The com.gather.struts.LogTypeForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.LogType logTypePersistence,
			com.gather.struts.forms.LogTypeForm logTypeForm) throws Exception {
		// Persistence layer specific implementation
		logTypePersistence.setLogTypeId(logTypeForm.getLogTypeId());
		logTypePersistence.setLogType(logTypeForm.getLogType());
	}

	/**
	 * Copy data from a com.gather.hibernate.LogType object into a
	 * com.gather.struts.LogTypeForm value object.
	 * 
	 * @param logTypePersistence
	 *            The com.gather.hibernate.LogType object from which the data is
	 *            to be copied.
	 * @param logTypeForm
	 *            The com.gather.struts.LogTypeForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.LogType logTypePersistence,
			com.gather.struts.forms.LogTypeForm logTypeForm) throws Exception {
		// Persistence layer specific implementation
		logTypeForm.setLogTypeId(logTypePersistence.getLogTypeId());
		logTypeForm.setLogType(logTypePersistence.getLogType());
	}

	/**
	 * Copy data from a com.gather.struts.MappingRelationForm value object into
	 * a com.gather.hibernate.MappingRelation object.
	 * 
	 * @param mappingRelationPersistence
	 *            The com.gather.hibernate.MappingRelation object into which the
	 *            data is to be copied.
	 * @param mappingRelationForm
	 *            The com.gather.struts.MappingRelationForm value object
	 *            containing the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MappingRelation mappingRelationPersistence,
			com.gather.struts.forms.MappingRelationForm mappingRelationForm)
			throws Exception {
		// Persistence layer specific implementation
		/*
		 * mappingRelationPersistence.getComp_id().setOrgid(mappingRelationForm.getOrgid());
		 * mappingRelationPersistence.getComp_id().setReplaceOrgId(mappingRelationForm.getReplaceOrgId());
		 */
		MappingRelationPK pk = new MappingRelationPK();
		pk.setOrgid(mappingRelationForm.getOrgid());
		pk.setReplaceOrgId(mappingRelationForm.getReplaceOrgId());
		mappingRelationPersistence.setComp_id(pk);
		mappingRelationPersistence.setStartDate(mappingRelationForm
				.getStartDate());
		mappingRelationPersistence.setEndDate(mappingRelationForm.getEndDate());
		mappingRelationPersistence.setState(mappingRelationForm.getState());
	}

	/**
	 * Copy data from a com.gather.hibernate.MappingRelation object into a
	 * com.gather.struts.MappingRelationForm value object.
	 * 
	 * @param mappingRelationPersistence
	 *            The com.gather.hibernate.MappingRelation object from which the
	 *            data is to be copied.
	 * @param mappingRelationForm
	 *            The com.gather.struts.MappingRelationForm value object into
	 *            which the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MappingRelation mappingRelationPersistence,
			com.gather.struts.forms.MappingRelationForm mappingRelationForm)
			throws Exception {
		// Persistence layer specific implementation
		if (mappingRelationPersistence.getMOrg() != null) {
			mappingRelationForm.setOrgid(mappingRelationPersistence.getMOrg()
					.getOrgId());
		}
		mappingRelationForm.setReplaceOrgId(mappingRelationPersistence
				.getComp_id().getReplaceOrgId());
		mappingRelationForm.setStartDate(mappingRelationPersistence
				.getStartDate());
		mappingRelationForm.setEndDate(mappingRelationPersistence.getEndDate());
		mappingRelationForm.setState(mappingRelationPersistence.getState());
	}

	/**
	 * Copy data from a com.gather.struts.CalendarDetailForm value object into a
	 * com.gather.hibernate.CalendarDetail object.
	 * 
	 * @param calendarDetailPersistence
	 *            The com.gather.hibernate.CalendarDetail object into which the
	 *            data is to be copied.
	 * @param calendarDetailForm
	 *            The com.gather.struts.CalendarDetailForm value object
	 *            containing the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.CalendarDetail calendarDetailPersistence,
			com.gather.struts.forms.CalendarDetailForm calendarDetailForm)
			throws Exception {
		CalendarDetailPK calendarDetailPK = new CalendarDetailPK();
		calendarDetailPK.setCalYear(calendarDetailForm.getCalYear());
		calendarDetailPK.setCalMonth(calendarDetailForm.getCalMonth());
		calendarDetailPK.setCalDay(calendarDetailForm.getCalDay());
		calendarDetailPK.setCalId(calendarDetailForm.getCalId());
		calendarDetailPK.setCalTypeId(calendarDetailForm.getCalTypeId());
		calendarDetailPersistence.setComp_id(calendarDetailPK);
		calendarDetailPersistence.setCalDate(calendarDetailForm.getCalDate());
	}

	/**
	 * Copy data from a com.gather.hibernate.CalendarDetail object into a
	 * com.gather.struts.CalendarDetailForm value object.
	 * 
	 * @param calendarDetailPersistence
	 *            The com.gather.hibernate.CalendarDetail object from which the
	 *            data is to be copied.
	 * @param calendarDetailForm
	 *            The com.gather.struts.CalendarDetailForm value object into
	 *            which the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.CalendarDetail calendarDetailPersistence,
			com.gather.struts.forms.CalendarDetailForm calendarDetailForm)
			throws Exception {
		// Persistence layer specific implementation
		calendarDetailForm.setCalYear(calendarDetailPersistence.getComp_id()
				.getCalYear());
		calendarDetailForm.setCalMonth(calendarDetailPersistence.getComp_id()
				.getCalMonth());
		calendarDetailForm.setCalDay(calendarDetailPersistence.getComp_id()
				.getCalDay());
		calendarDetailForm.setCalDate(calendarDetailPersistence.getCalDate());
		if (calendarDetailPersistence.getCalendar() != null) {
			calendarDetailForm.setCalId(calendarDetailPersistence.getCalendar()
					.getCalId());
		}
		if (calendarDetailPersistence.getCalendarType() != null) {
			calendarDetailForm.setCalTypeId(calendarDetailPersistence
					.getCalendarType().getCalTypeId());
		}
	}

	/**
	 * Copy data from a com.gather.struts.MCurUnitForm value object into a
	 * com.gather.hibernate.MCurUnit object.
	 * 
	 * @param mCurUnitPersistence
	 *            The com.gather.hibernate.MCurUnit object into which the data
	 *            is to be copied.
	 * @param mCurUnitForm
	 *            The com.gather.struts.MCurUnitForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MCurUnit mCurUnitPersistence,
			com.gather.struts.forms.MCurUnitForm mCurUnitForm) throws Exception {
		// Persistence layer specific implementation
		mCurUnitPersistence.setCurUnit(mCurUnitForm.getCurUnit());
		mCurUnitPersistence.setCurUnitName(mCurUnitForm.getCurUnitName());
	}

	/**
	 * Copy data from a com.gather.hibernate.MCurUnit object into a
	 * com.gather.struts.MCurUnitForm value object.
	 * 
	 * @param mCurUnitPersistence
	 *            The com.gather.hibernate.MCurUnit object from which the data
	 *            is to be copied.
	 * @param mCurUnitForm
	 *            The com.gather.struts.MCurUnitForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MCurUnit mCurUnitPersistence,
			com.gather.struts.forms.MCurUnitForm mCurUnitForm) throws Exception {
		// Persistence layer specific implementation
		mCurUnitForm.setCurUnit(mCurUnitPersistence.getCurUnit());
		mCurUnitForm.setCurUnitName(mCurUnitPersistence.getCurUnitName());
	}

	/**
	 * Copy data from a com.gather.struts.OtherFileForm value object into a
	 * com.gather.hibernate.OtherFile object.
	 * 
	 * @param otherFilePersistence
	 *            The com.gather.hibernate.OtherFile object into which the data
	 *            is to be copied.
	 * @param otherFileForm
	 *            The com.gather.struts.OtherFileForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.OtherFile otherFilePersistence,
			com.gather.struts.forms.OtherFileForm otherFileForm)
			throws Exception {
		// Persistence layer specific implementation
		otherFilePersistence.setOtherFileId(otherFileForm.getOtherFileId());
		otherFilePersistence.setOrgId(otherFileForm.getOrgId());
		otherFilePersistence.setUpReportDate(otherFileForm.getUpReportDate());
		otherFilePersistence.setFileName(otherFileForm.getFileName());
		otherFilePersistence.setOperator(otherFileForm.getOperator());
	}

	/**
	 * Copy data from a com.gather.hibernate.OtherFile object into a
	 * com.gather.struts.OtherFileForm value object.
	 * 
	 * @param otherFilePersistence
	 *            The com.gather.hibernate.OtherFile object from which the data
	 *            is to be copied.
	 * @param otherFileForm
	 *            The com.gather.struts.OtherFileForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.OtherFile otherFilePersistence,
			com.gather.struts.forms.OtherFileForm otherFileForm)
			throws Exception {
		// Persistence layer specific implementation
		otherFileForm.setOtherFileId(otherFilePersistence.getOtherFileId());
		otherFileForm.setOrgId(otherFilePersistence.getOrgId());
		otherFileForm.setUpReportDate(otherFilePersistence.getUpReportDate());
		otherFileForm.setFileName(otherFilePersistence.getFileName());
		otherFileForm.setOperator(otherFilePersistence.getOperator());
	}

	/**
	 * Copy data from a com.gather.struts.MRepdescForm value object into a
	 * com.gather.hibernate.MRepdesc object.
	 * 
	 * @param mRepdescPersistence
	 *            The com.gather.hibernate.MRepdesc object into which the data
	 *            is to be copied.
	 * @param mRepdescForm
	 *            The com.gather.struts.MRepdescForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MRepdesc mRepdescPersistence,
			com.gather.struts.forms.MRepdescForm mRepdescForm) throws Exception {
		// Persistence layer specific implementation
		mRepdescPersistence.getComp_id().setReportdate(
				mRepdescForm.getReportdate());
		mRepdescPersistence.setTerm(mRepdescForm.getTerm());
		mRepdescPersistence.setTorepdate(mRepdescForm.getTorepdate());
		mRepdescPersistence.setMkreppers(mRepdescForm.getMkreppers());
		mRepdescPersistence.setCkreppers(mRepdescForm.getCkreppers());
		mRepdescPersistence.setCgreppers(mRepdescForm.getCgreppers());
		if (mRepdescPersistence.getMDataRgType() != null) {
			mRepdescPersistence.getMDataRgType().setDataRangeId(
					mRepdescForm.getDatarangeid());
		}
		if (mRepdescPersistence.getMMainRep() != null) {
			mRepdescPersistence.getMMainRep().setRepId(mRepdescForm.getRepid());
		}
		mRepdescPersistence.getComp_id().setOrgid(mRepdescForm.getOrgid());
	}

	/**
	 * Copy data from a com.gather.hibernate.MRepdesc object into a
	 * com.gather.struts.MRepdescForm value object.
	 * 
	 * @param mRepdescPersistence
	 *            The com.gather.hibernate.MRepdesc object from which the data
	 *            is to be copied.
	 * @param mRepdescForm
	 *            The com.gather.struts.MRepdescForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MRepdesc mRepdescPersistence,
			com.gather.struts.forms.MRepdescForm mRepdescForm) throws Exception {
		// Persistence layer specific implementation
		mRepdescForm.setReportdate(mRepdescPersistence.getComp_id()
				.getReportdate());
		mRepdescForm.setTerm(mRepdescPersistence.getTerm());
		mRepdescForm.setTorepdate(mRepdescPersistence.getTorepdate());
		mRepdescForm.setMkreppers(mRepdescPersistence.getMkreppers());
		mRepdescForm.setCkreppers(mRepdescPersistence.getCkreppers());
		mRepdescForm.setCgreppers(mRepdescPersistence.getCgreppers());
		if (mRepdescPersistence.getMDataRgType() != null) {
			mRepdescForm.setDatarangeid(mRepdescPersistence.getMDataRgType()
					.getDataRangeId());
		}
		if (mRepdescPersistence.getMMainRep() != null) {
			mRepdescForm.setRepid(mRepdescPersistence.getMMainRep().getRepId());
		}
		mRepdescForm.setOrgid(mRepdescPersistence.getComp_id().getOrgid());
	}

	/**
	 * Copy data from a com.gather.struts.RepRangeDownLogForm value object into
	 * a com.gather.hibernate.RepRangeDownLog object.
	 * 
	 * @param repRangeDownLogPersistence
	 *            The com.gather.hibernate.RepRangeDownLog object into which the
	 *            data is to be copied.
	 * @param repRangeDownLogForm
	 *            The com.gather.struts.RepRangeDownLogForm value object
	 *            containing the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.RepRangeDownLog repRangeDownLogPersistence,
			com.gather.struts.forms.RepRangeDownLogForm repRangeDownLogForm)
			throws Exception {
		// Persistence layer specific implementation
		RepRangeDownLogPK pk = new RepRangeDownLogPK();
		/*
		 * repRangeDownLogPersistence.getComp_id().setOrgId(repRangeDownLogForm.getOrgId());
		 * repRangeDownLogPersistence.getComp_id().setChildRepId(repRangeDownLogForm.getChildRepId());
		 * repRangeDownLogPersistence.getComp_id().setVersionId(repRangeDownLogForm.getVersionId());
		 */
		repRangeDownLogPersistence.setState(repRangeDownLogForm.getState());
		pk.setOrgId(repRangeDownLogForm.getOrgId());
		pk.setChildRepId(repRangeDownLogForm.getChildRepId());
		pk.setVersionId(repRangeDownLogForm.getVersionId());
		repRangeDownLogPersistence.setComp_id(pk);

	}

	/**
	 * Copy data from a com.gather.hibernate.RepRangeDownLog object into a
	 * com.gather.struts.RepRangeDownLogForm value object.
	 * 
	 * @param repRangeDownLogPersistence
	 *            The com.gather.hibernate.RepRangeDownLog object from which the
	 *            data is to be copied.
	 * @param repRangeDownLogForm
	 *            The com.gather.struts.RepRangeDownLogForm value object into
	 *            which the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.RepRangeDownLog repRangeDownLogPersistence,
			com.gather.struts.forms.RepRangeDownLogForm repRangeDownLogForm)
			throws Exception {
		// Persistence layer specific implementation
		repRangeDownLogForm.setOrgId(repRangeDownLogPersistence.getComp_id()
				.getOrgId());
		repRangeDownLogForm.setChildRepId(repRangeDownLogPersistence
				.getComp_id().getChildRepId());
		repRangeDownLogForm.setVersionId(repRangeDownLogPersistence
				.getComp_id().getVersionId());
		repRangeDownLogForm.setState(repRangeDownLogPersistence.getState());
	}

	/**
	 * Copy data from a com.gather.struts.MCellFormForm value object into a
	 * com.gather.hibernate.MCellForm object.
	 * 
	 * @param mCellFormPersistence
	 *            The com.gather.hibernate.MCellForm object into which the data
	 *            is to be copied.
	 * @param mCellFormForm
	 *            The com.gather.struts.MCellFormForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.MCellForm mCellFormPersistence,
			com.gather.struts.forms.MCellFormForm mCellFormForm)
			throws Exception {
		// Persistence layer specific implementation
		mCellFormPersistence.setCellFormId(mCellFormForm.getCellFormId());
		mCellFormPersistence.setCellForm(mCellFormForm.getCellForm());
		mCellFormPersistence.setFormType(mCellFormForm.getFormType());
	}

	/**
	 * Copy data from a com.gather.hibernate.MCellForm object into a
	 * com.gather.struts.MCellFormForm value object.
	 * 
	 * @param mCellFormPersistence
	 *            The com.gather.hibernate.MCellForm object from which the data
	 *            is to be copied.
	 * @param mCellFormForm
	 *            The com.gather.struts.MCellFormForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.MCellForm mCellFormPersistence,
			com.gather.struts.forms.MCellFormForm mCellFormForm)
			throws Exception {
		// Persistence layer specific implementation
		mCellFormForm.setCellFormId(mCellFormPersistence.getCellFormId());
		mCellFormForm.setCellForm(mCellFormPersistence.getCellForm());
		mCellFormForm.setFormType(mCellFormPersistence.getFormType());
	}

	/**
	 * Copy data from a com.gather.struts.NoticeForm value object into a
	 * com.gather.hibernate.Notice object.
	 * 
	 * @param noticePersistence
	 *            The com.gather.hibernate.Notice object into which the data is
	 *            to be copied.
	 * @param noticeForm
	 *            The com.gather.struts.NoticeForm value object containing the
	 *            data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.Notice noticePersistence,
			com.gather.struts.forms.NoticeForm noticeForm) throws Exception {
		// Persistence layer specific implementation
		noticePersistence.setNoticeId(noticeForm.getNoticeId());
		noticePersistence.setNoticeTitle(noticeForm.getNoticeTitle());
		noticePersistence.setContent(noticeForm.getContent());
		noticePersistence.setPublishTime(noticeForm.getPublishTime());
		noticePersistence.setState(noticeForm.getState());
	}

	/**
	 * Copy data from a com.gather.hibernate.Notice object into a
	 * com.gather.struts.NoticeForm value object.
	 * 
	 * @param noticePersistence
	 *            The com.gather.hibernate.Notice object from which the data is
	 *            to be copied.
	 * @param noticeForm
	 *            The com.gather.struts.NoticeForm value object into which the
	 *            data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.Notice noticePersistence,
			com.gather.struts.forms.NoticeForm noticeForm) throws Exception {
		// Persistence layer specific implementation
		noticeForm.setNoticeId(noticePersistence.getNoticeId());
		noticeForm.setNoticeTitle(noticePersistence.getNoticeTitle());
		noticeForm.setContent(noticePersistence.getContent());
		noticeForm.setPublishTime(noticePersistence.getPublishTime());
		noticeForm.setState(noticePersistence.getState());
	}

	/**
	 * Copy data from a com.gather.struts.CalendarTypeForm value object into a
	 * com.gather.hibernate.CalendarType object.
	 * 
	 * @param calendarTypePersistence
	 *            The com.gather.hibernate.CalendarType object into which the
	 *            data is to be copied.
	 * @param calendarTypeForm
	 *            The com.gather.struts.CalendarTypeForm value object containing
	 *            the data to be copied.
	 */
	protected static void copyVoToPersistence(
			com.gather.hibernate.CalendarType calendarTypePersistence,
			com.gather.struts.forms.CalendarTypeForm calendarTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		calendarTypePersistence.setCalTypeId(calendarTypeForm.getCalTypeId());
		calendarTypePersistence.setCalTypeName(calendarTypeForm
				.getCalTypeName());
	}

	/**
	 * Copy data from a com.gather.hibernate.CalendarType object into a
	 * com.gather.struts.CalendarTypeForm value object.
	 * 
	 * @param calendarTypePersistence
	 *            The com.gather.hibernate.CalendarType object from which the
	 *            data is to be copied.
	 * @param calendarTypeForm
	 *            The com.gather.struts.CalendarTypeForm value object into which
	 *            the data is to be copied.
	 */
	protected static void copyPersistenceToVo(
			com.gather.hibernate.CalendarType calendarTypePersistence,
			com.gather.struts.forms.CalendarTypeForm calendarTypeForm)
			throws Exception {
		// Persistence layer specific implementation
		calendarTypeForm.setCalTypeId(calendarTypePersistence.getCalTypeId());
		calendarTypeForm.setCalTypeName(calendarTypePersistence
				.getCalTypeName());
	}
}
