
package com.gather.adapter;


/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for DownloadResource data (i.e. 
 * com.gather.struts.DownloadResourceForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsDownloadResourceDelegate {

//暂时没有任何方法
 }
