
package com.gather.adapter;

import net.sf.hibernate.Session;

import com.gather.common.Log;
import com.gather.dao.DBConn;
/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MRepType data (i.e. 
 * com.gather.struts.forms.MRepTypeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMRepTypeDelegate {


   /**
    * Create a new com.gather.struts.forms.MRepTypeForm object and persist (i.e. insert) it.
    *
    * @param   mRepTypeForm   The object containing the data for the new com.gather.struts.forms.MRepTypeForm object
    * @exception   Exception   If the new com.gather.struts.forms.MRepTypeForm object cannot be created or persisted.
    */
   public static boolean create (com.gather.struts.forms.MRepTypeForm mRepTypeForm) throws Exception {
      com.gather.hibernate.MRepType mRepTypePersistence = new com.gather.hibernate.MRepType ();
      try{
    	  TranslatorUtil.copyVoToPersistence(mRepTypePersistence, mRepTypeForm);
    	  DBConn conn=new DBConn();
    	  Session session=conn.beginTransaction();
    	  session.save(mRepTypePersistence);
    	  conn.endTransaction(true);
    	  return true;
      }catch(Exception e)
      {
    	  new Log(StrutsMRepTypeDelegate.class).info(":::class:StrutsMRepTypeDelegate --  method: create “Ï≥££∫"+e.getMessage());
    	  throw e;
      }
   }
}
