
package com.gather.adapter;


/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for ResourceType data (i.e. 
 * com.gather.struts.forms.ResourceTypeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsResourceTypeDelegate {

//暂时无方法
}
