package com.cbrc.auth.adapter;

import java.util.Date;

import com.cbrc.auth.hibernate.Department;
import com.cbrc.auth.util.Encoder;
import com.fitech.net.hibernate.OrgNet;

/**
 * This is a utilitiy class to handle value object conversion between the 
 * backend persistence layer and the frontend action layer. It has a set of 
 * methods to handle conversions.
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class TranslatorUtil {


   /**
    * Copy data from a com.cbrc.auth.form.DepartmentForm value object into a com.cbrc.auth.hibernate.Department object.
    *
    * @param   departmentPersistence   The com.cbrc.auth.hibernate.Department object into which the data is to be copied.
    * @param   departmentForm   The com.cbrc.auth.form.DepartmentForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.Department departmentPersistence, com.cbrc.auth.form.DepartmentForm departmentForm) throws Exception {
      // Persistence layer specific implementation
       //   departmentPersistence.setDepartmentId(departmentForm.getDepartmentId());
              departmentPersistence.setDeptName(departmentForm.getDeptName());
           // departmentPersistence.setProductUserId(departmentForm.getProductUserId());
     }

   /**
    * Copy data from a com.cbrc.auth.hibernate.Department object into a com.cbrc.auth.form.DepartmentForm value object.
    *
    * @param   departmentPersistence   The com.cbrc.auth.hibernate.Department object from which the data is to be copied.
    * @param   departmentForm   The com.cbrc.auth.form.DepartmentForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.Department departmentPersistence, com.cbrc.auth.form.DepartmentForm departmentForm) throws Exception {
      // Persistence layer specific implementation
          departmentForm.setDepartmentId(departmentPersistence.getDepartmentId());
          departmentForm.setDeptName(departmentPersistence.getDeptName());
        //  departmentForm.setProductUserId(departmentPersistence.getProductUser().getProductUserId());
          
     }

   /**
    * Copy data from a com.cbrc.auth.form.RoleToolForm value object into a com.cbrc.auth.hibernate.RoleTool object.
    *
    * @param   roleToolPersistence   The com.cbrc.auth.hibernate.RoleTool object into which the data is to be copied.
    * @param   roleToolForm   The com.cbrc.auth.form.RoleToolForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.RoleTool roleToolPersistence, com.cbrc.auth.form.RoleToolForm roleToolForm) throws Exception {
      // Persistence layer specific implementation
          roleToolPersistence.setRoleToolId(roleToolForm.getRoleToolId());
           /* roleToolPersistence.setRoleId(roleToolForm.getRoleId());
            roleToolPersistence.setMenuId(roleToolForm.getMenuId());*/
     }

   /**
    * Copy data from a com.cbrc.auth.hibernate.RoleTool object into a com.cbrc.auth.form.RoleToolForm value object.
    *
    * @param   roleToolPersistence   The com.cbrc.auth.hibernate.RoleTool object from which the data is to be copied.
    * @param   roleToolForm   The com.cbrc.auth.form.RoleToolForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.RoleTool roleToolPersistence, com.cbrc.auth.form.RoleToolForm roleToolForm) throws Exception {
      // Persistence layer specific implementation
          roleToolForm.setRoleToolId(roleToolPersistence.getRoleToolId());
          roleToolForm.setRoleId(roleToolPersistence.getRole().getRoleId());
            roleToolForm.setMenuId(roleToolPersistence.getToolSetting().getMenuId());
            roleToolForm.setMenuName(roleToolPersistence.getToolSetting().getMenuName());
     }

   /**
    * Copy data from a com.cbrc.auth.form.ProductUserForm value object into a com.cbrc.auth.hibernate.ProductUser object.
    *
    * @param   productUserPersistence   The com.cbrc.auth.hibernate.ProductUser object into which the data is to be copied.
    * @param   productUserForm   The com.cbrc.auth.form.ProductUserForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.ProductUser productUserPersistence, com.cbrc.auth.form.ProductUserForm productUserForm) throws Exception {
      // Persistence layer specific implementation
          productUserPersistence.setProductUserId(productUserForm.getProductUserId());
          productUserPersistence.setProductUserName(productUserForm.getProductUserName());
   }

   /**
    * Copy data from a com.cbrc.auth.hibernate.ProductUser object into a com.cbrc.auth.form.ProductUserForm value object.
    *
    * @param   productUserPersistence   The com.cbrc.auth.hibernate.ProductUser object from which the data is to be copied.
    * @param   productUserForm   The com.cbrc.auth.form.ProductUserForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.ProductUser productUserPersistence, com.cbrc.auth.form.ProductUserForm productUserForm) throws Exception {
      // Persistence layer specific implementation
          productUserForm.setProductUserId(productUserPersistence.getProductUserId());
          productUserForm.setProductUserName(productUserPersistence.getProductUserName());
   }

   /**
    * Copy data from a com.cbrc.auth.form.OperatorForm value object into a com.cbrc.auth.hibernate.Operator object.
    *
    * @param   operatorPersistence   The com.cbrc.auth.hibernate.Operator object into which the data is to be copied.
    * @param   operatorForm   The com.cbrc.auth.form.OperatorForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.Operator operatorPersistence, com.cbrc.auth.form.OperatorForm operatorForm) throws Exception {      
	   // Persistence layer specific implementation        
       if(operatorForm.getPassword()!=null && !operatorForm.getPassword().equals("")){
    	   /**◊¢ ÕµÙ√‹¬Îº”√‹*/
    	   operatorPersistence.setPassword(Encoder.getMD5_Base64(operatorForm.getPassword()));       
       }       
       operatorPersistence.setUserName(operatorForm.getUserName().trim());       
       operatorPersistence.setFirstName(operatorForm.getFirstName().trim());       
       operatorPersistence.setLastName(operatorForm.getLastName().trim());       
       operatorPersistence.setMail(operatorForm.getMail().trim());       
       operatorPersistence.setIdentificationNumber(operatorForm.getIdentificationNumber());       
       operatorPersistence.setEmployeeNumber(operatorForm.getEmployeeNumber());       
       operatorPersistence.setTitle(operatorForm.getTitle().trim());       
       operatorPersistence.setEmployeeType(operatorForm.getEmployeeType());       
       operatorPersistence.setBranch(operatorForm.getBranch());       
       operatorPersistence.setAddress(operatorForm.getAddress());       
       operatorPersistence.setPostalAddress(operatorForm.getPostalAddress());       
       operatorPersistence.setPostalCode(operatorForm.getPostalCode());       
       operatorPersistence.setFax(operatorForm.getFax());       
       operatorPersistence.setTelephoneNumber(operatorForm.getTelephoneNumber());       
       operatorPersistence.setManager(operatorForm.getManager());       
       operatorPersistence.setSex(operatorForm.getSex());       
       operatorPersistence.setAge(operatorForm.getAge());       
       operatorPersistence.setGroupNumber(operatorForm.getGroupNumber());       
       operatorPersistence.setUpdateTime(new Date());
       
       if(operatorForm.getOrgId() != null){       
    	   OrgNet orgNet = new OrgNet();        	
    	   orgNet.setOrgId(operatorForm.getOrgId());        	
    	   operatorPersistence.setOrg(orgNet);        
       }        
       if(operatorForm.getSetOrgId() != null){        
    	   OrgNet orgNet = new OrgNet();        	
    	   orgNet.setOrgId(operatorForm.getSetOrgId());        	
    	   operatorPersistence.setSetOrg(orgNet);        
       }        
       if(operatorForm.getDepartmentId() != null && !operatorForm.getDepartmentId().equals("")){       
    	   Department dept = new Department();        	
    	   dept.setDepartmentId(operatorForm.getDepartmentId());           
    	   operatorPersistence.setDepartment(dept);        
       }    
   }

   /**
     * Copy data from a com.cbrc.auth.hibernate.Operator object into a
     * com.cbrc.auth.form.OperatorForm value object.
     * 
     * @param operatorPersistence
     *            The com.cbrc.auth.hibernate.Operator object from which the
     *            data is to be copied.
     * @param operatorForm
     *            The com.cbrc.auth.form.OperatorForm value object into which
     *            the data is to be copied.
     */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.Operator operatorPersistence, com.cbrc.auth.form.OperatorForm operatorForm) throws Exception {
      // Persistence layer specific implementation
          operatorForm.setUserId(operatorPersistence.getUserId());
        operatorForm.setPassword(operatorPersistence.getPassword());
        operatorForm.setUserName(operatorPersistence.getUserName());
        operatorForm.setFirstName(operatorPersistence.getFirstName());
        operatorForm.setLastName(operatorPersistence.getLastName());
        operatorForm.setMail(operatorPersistence.getMail());
        operatorForm.setIdentificationNumber(operatorPersistence.getIdentificationNumber());
        operatorForm.setEmployeeNumber(operatorPersistence.getEmployeeNumber());
        operatorForm.setTitle(operatorPersistence.getTitle());
        operatorForm.setEmployeeType(operatorPersistence.getEmployeeType());
        operatorForm.setBranch(operatorPersistence.getBranch());
        operatorForm.setAddress(operatorPersistence.getAddress());
        operatorForm.setPostalAddress(operatorPersistence.getPostalAddress());
        operatorForm.setPostalCode(operatorPersistence.getPostalCode());
        operatorForm.setFax(operatorPersistence.getFax());
        operatorForm.setTelephoneNumber(operatorPersistence.getTelephoneNumber());
        operatorForm.setManager(operatorPersistence.getManager());
        operatorForm.setSex(operatorPersistence.getSex());
        operatorForm.setAge(operatorPersistence.getAge());
        operatorForm.setGroupNumber(operatorPersistence.getGroupNumber());
        operatorForm.setUpdateTime(operatorPersistence.getUpdateTime());
        operatorForm.setSuperManager(operatorPersistence.getSuperManager());       
        if(operatorPersistence.getDepartment()!=null){
        	operatorForm.setDepartmentId(operatorPersistence.getDepartment().getDepartmentId());        
        	operatorForm.setDeptName(operatorPersistence.getDepartment().getDeptName());
        	if(operatorPersistence.getDepartment().getProductUser() != null)
        		operatorForm.setProductUserName(operatorPersistence.getDepartment().getProductUser().getProductUserName());        
        }
        
        if(operatorPersistence.getSetOrg() != null){
        	operatorForm.setSetOrgId(operatorPersistence.getSetOrg().getOrgId());
        	operatorForm.setSetOrgName(operatorPersistence.getSetOrg().getOrgName());
        }
        
        if(operatorPersistence.getOrg() != null){
        	operatorForm.setOrgId(operatorPersistence.getOrg().getOrgId());
        	operatorForm.setOrgName(operatorPersistence.getOrg().getOrgName());
        }        
     }

   /**
     * Copy data from a com.cbrc.auth.form.MUserToGrpForm value object into a
     * com.cbrc.auth.hibernate.MUserToGrp object.
     * 
     * @param mUserToGrpPersistence
     *            The com.cbrc.auth.hibernate.MUserToGrp object into which the
     *            data is to be copied.
     * @param mUserToGrpForm
     *            The com.cbrc.auth.form.MUserToGrpForm value object containing
     *            the data to be copied.
     */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.MUserToGrp mUserToGrpPersistence, com.cbrc.auth.form.MUserToGrpForm mUserToGrpForm) throws Exception {
      /*// Persistence layer specific implementation
          mUserToGrpPersistence.setUserToGrpId().setUserGrpId(mUserToGrpForm.getUserGrpId());
          mUserToGrpPersistence.setUserId(mUserToGrpForm.getUserId());*/
     }

   /**
    * Copy data from a com.cbrc.auth.hibernate.MUserToGrp object into a com.cbrc.auth.form.MUserToGrpForm value object.
    *
    * @param   mUserToGrpPersistence   The com.cbrc.auth.hibernate.MUserToGrp object from which the data is to be copied.
    * @param   mUserToGrpForm   The com.cbrc.auth.form.MUserToGrpForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.MUserToGrp mUserToGrpPersistence, com.cbrc.auth.form.MUserToGrpForm mUserToGrpForm) throws Exception {
      // Persistence layer specific implementation
          mUserToGrpForm.setUserToGrpId(mUserToGrpPersistence.getUserToGrpId());
          mUserToGrpForm.setUserGrpId(mUserToGrpPersistence.getMUserGrp().getUserGrpId());
          mUserToGrpForm.setUserGrpNm(mUserToGrpPersistence.getMUserGrp().getUserGrpNm());
          mUserToGrpForm.setUserId(mUserToGrpPersistence.getOperator().getUserId());
          
     }

   /**
    * Copy data from a com.cbrc.auth.form.UserRoleForm value object into a com.cbrc.auth.hibernate.UserRole object.
    *
    * @param   userRolePersistence   The com.cbrc.auth.hibernate.UserRole object into which the data is to be copied.
    * @param   userRoleForm   The com.cbrc.auth.form.UserRoleForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.UserRole userRolePersistence, com.cbrc.auth.form.UserRoleForm userRoleForm) throws Exception {
      // Persistence layer specific implementation
          userRolePersistence.setUserRoleId(userRoleForm.getUserRoleId());
            /*userRolePersistence.setRoleId(userRoleForm.getRoleId());
            userRolePersistence.setUserId(userRoleForm.getUserId());*/
     }

   /**
    * Copy data from a com.cbrc.auth.hibernate.UserRole object into a com.cbrc.auth.form.UserRoleForm value object.
    *
    * @param   userRolePersistence   The com.cbrc.auth.hibernate.UserRole object from which the data is to be copied.
    * @param   userRoleForm   The com.cbrc.auth.form.UserRoleForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.UserRole userRolePersistence, com.cbrc.auth.form.UserRoleForm userRoleForm) throws Exception {
      // Persistence layer specific implementation
          userRoleForm.setUserRoleId(userRolePersistence.getUserRoleId());
          userRoleForm.setRoleId(userRolePersistence.getRole().getRoleId());
          userRoleForm.setUserId(userRolePersistence.getOperator().getUserId());
          userRoleForm.setRoleName(userRolePersistence.getRole().getRoleName());
     }

   /**
    * Copy data from a com.cbrc.auth.form.MPurViewForm value object into a com.cbrc.auth.hibernate.MPurView object.
    *
    * @param   mPurViewPersistence   The com.cbrc.auth.hibernate.MPurView object into which the data is to be copied.
    * @param   mPurViewForm   The com.cbrc.auth.form.MPurViewForm value object containing the data to be copied. 
    */
//   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.MPurView mPurViewPersistence, com.cbrc.auth.form.MPurViewForm mPurViewForm) throws Exception {
//      // Persistence layer specific implementation
//                      /*mPurViewPersistence.setUserGrpId(mPurViewForm.getUserGrpId());
//            mPurViewPersistence.setOrgId(mPurViewForm.getOrgId());
//            mPurViewPersistence.setChildRepId(mPurViewForm.getChildRepId());
//            mPurViewPersistence.setDataRangeId(mPurViewForm.getDataRangeId());*/
//     }

   /**
    * Copy data from a com.cbrc.auth.hibernate.MPurView object into a com.cbrc.auth.form.MPurViewForm value object.
    *
    * @param   mPurViewPersistence   The com.cbrc.auth.hibernate.MPurView object from which the data is to be copied.
    * @param   mPurViewForm   The com.cbrc.auth.form.MPurViewForm value object into which the data is to be copied.   
    */
//   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.MPurView mPurViewPersistence, com.cbrc.auth.form.MPurViewForm mPurViewForm) throws Exception {
//      // Persistence layer specific implementation
//           mPurViewForm.setUserGrpId(mPurViewPersistence.getComp_id().getUserGrpId());
//           mPurViewForm.setOrgId(mPurViewPersistence.getComp_id().getOrgId());
//           mPurViewForm.setChildRepId(mPurViewPersistence.getComp_id().getChildRepId());
//           
//     }
   
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.MBankLevel mBankLevelPersistence, com.cbrc.auth.form.MBankLevelForm mBankLevelForm) throws Exception {
	   mBankLevelPersistence.setBankLevelId(mBankLevelForm.getBankLevelId());
	   mBankLevelPersistence.setBankLevelName(mBankLevelForm.getBankLevelName());
   }
   
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.MBankLevel mBankLevelPersistence, com.cbrc.auth.form.MBankLevelForm mBankLevelForm) throws Exception {	   
	   mBankLevelForm.setBankLevelId(mBankLevelPersistence.getBankLevelId());
	   mBankLevelForm.setBankLevelName(mBankLevelPersistence.getBankLevelName());	  
   }
   /**
    * Copy data from a com.cbrc.auth.form.MUserGrpForm value object into a com.cbrc.auth.hibernate.MUserGrp object.
    *
    * @param   mUserGrpPersistence   The com.cbrc.auth.hibernate.MUserGrp object into which the data is to be copied.
    * @param   mUserGrpForm   The com.cbrc.auth.form.MUserGrpForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.MUserGrp mUserGrpPersistence, com.cbrc.auth.form.MUserGrpForm mUserGrpForm) throws Exception {
      // Persistence layer specific implementation          
	   mUserGrpPersistence.setUserGrpId(mUserGrpForm.getUserGrpId());       
	   mUserGrpPersistence.setUserGrpNm(mUserGrpForm.getUserGrpNm().trim());
       OrgNet orgNet = new OrgNet();
       orgNet.setOrgId(mUserGrpForm.getSetOrgId().trim());
       orgNet.setOrgName(mUserGrpForm.getSetOrgName() != null ? mUserGrpForm.getSetOrgName().trim() : null);
       mUserGrpPersistence.setSetOrg(orgNet);
   }

   /**
    * Copy data from a com.cbrc.auth.hibernate.MUserGrp object into a com.cbrc.auth.form.MUserGrpForm value object.
    *
    * @param   mUserGrpPersistence   The com.cbrc.auth.hibernate.MUserGrp object from which the data is to be copied.
    * @param   mUserGrpForm   The com.cbrc.auth.form.MUserGrpForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.MUserGrp mUserGrpPersistence, com.cbrc.auth.form.MUserGrpForm mUserGrpForm) throws Exception {
      // Persistence layer specific implementation          
	   mUserGrpForm.setUserGrpId(mUserGrpPersistence.getUserGrpId());                             
	   mUserGrpForm.setUserGrpNm(mUserGrpPersistence.getUserGrpNm().trim());
	   OrgNet orgNet = mUserGrpPersistence.getSetOrg();
	   if(orgNet != null){
		   mUserGrpForm.setSetOrgId(orgNet.getOrgId().trim());
		   mUserGrpForm.setSetOrgName(orgNet.getOrgName().trim());
	   }	   
   }

   /**
    * Copy data from a com.cbrc.auth.form.RoleForm value object into a com.cbrc.auth.hibernate.Role object.
    *
    * @param   rolePersistence   The com.cbrc.auth.hibernate.Role object into which the data is to be copied.
    * @param   roleForm   The com.cbrc.auth.form.RoleForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.Role rolePersistence, com.cbrc.auth.form.RoleForm roleForm) throws Exception {      
	   // Persistence layer specific implementation          
	   rolePersistence.setRoleId(roleForm.getRoleId());       
	   rolePersistence.setRoleName(roleForm.getRoleName());
	   rolePersistence.setSetOrgId(roleForm.getSetOrgId());
	   
   }

   /**
    * Copy data from a com.cbrc.auth.hibernate.Role object into a com.cbrc.auth.form.RoleForm value object.
    *
    * @param   rolePersistence   The com.cbrc.auth.hibernate.Role object from which the data is to be copied.
    * @param   roleForm   The com.cbrc.auth.form.RoleForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.Role rolePersistence, com.cbrc.auth.form.RoleForm roleForm) throws Exception {
       // Persistence layer specific implementation          
	   roleForm.setRoleId(rolePersistence.getRoleId());       
	   roleForm.setRoleName(rolePersistence.getRoleName());
	   roleForm.setSetOrgId(rolePersistence.getSetOrgId());
  }

   /**
    * Copy data from a com.cbrc.auth.form.ToolSettingForm value object into a com.cbrc.auth.hibernate.ToolSetting object.
    *
    * @param   toolSettingPersistence   The com.cbrc.auth.hibernate.ToolSetting object into which the data is to be copied.
    * @param   toolSettingForm   The com.cbrc.auth.form.ToolSettingForm value object containing the data to be copied. 
    */
   protected static void copyVoToPersistence(com.cbrc.auth.hibernate.ToolSetting toolSettingPersistence, com.cbrc.auth.form.ToolSettingForm toolSettingForm) throws Exception {      
	   // Persistence layer specific implementation       
	   toolSettingPersistence.setMenuId(toolSettingForm.getMenuId());       
	   toolSettingPersistence.setMenuName(toolSettingForm.getMenuName());       
	   toolSettingPersistence.setFunctionName(toolSettingForm.getFunctionName());       
	   toolSettingPersistence.setUrl(toolSettingForm.getUrl());       
	   toolSettingPersistence.setPriorId(toolSettingForm.getPriorId());	 	  
   }

   /**
    * Copy data from a com.cbrc.auth.hibernate.ToolSetting object into a com.cbrc.auth.form.ToolSettingForm value object.
    *
    * @param   toolSettingPersistence   The com.cbrc.auth.hibernate.ToolSetting object from which the data is to be copied.
    * @param   toolSettingForm   The com.cbrc.auth.form.ToolSettingForm value object into which the data is to be copied.   
    */
   protected static void copyPersistenceToVo(com.cbrc.auth.hibernate.ToolSetting toolSettingPersistence, com.cbrc.auth.form.ToolSettingForm toolSettingForm) throws Exception {      
	   // Persistence layer specific implementation       
	   toolSettingForm.setMenuId(toolSettingPersistence.getMenuId());       
	   toolSettingForm.setMenuName(toolSettingPersistence.getMenuName());       
	   toolSettingForm.setFunctionName(toolSettingPersistence.getFunctionName());       
	   toolSettingForm.setUrl(toolSettingPersistence.getUrl());       
	   toolSettingForm.setPriorId(toolSettingPersistence.getPriorId());       
   }
}
