/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Nov 14 21:20:11 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.fitech.net.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the COLLECT_TYPE table. 
 * You can customize the behavior of this class by editing the class, {@link CollectType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class CollectType implements Serializable{
	/** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private CollectTypeKey id;

    /** The value of the simple preColumn1 property. */
    private java.lang.String preColumn1;

    /** The value of the simple preColumn2 property. */
    private java.lang.String preColumn2;

    /**
     * Simple constructor of AbstractCollectType instances.
     */
    public CollectType()
    {
    }

    /**
     * Constructor of AbstractCollectType instances given a composite primary key.
     * @param id
     */
    public CollectType(CollectTypeKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return CollectTypeKey
     */
    public CollectTypeKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(CollectTypeKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the PRE_COLUMN1 column.
     * @return java.lang.String
     */
    public java.lang.String getPreColumn1()
    {
        return this.preColumn1;
    }

    /**
     * Set the value of the PRE_COLUMN1 column.
     * @param preColumn1
     */
    public void setPreColumn1(java.lang.String preColumn1)
    {
        this.preColumn1 = preColumn1;
    }

    /**
     * Return the value of the PRE_COLUMN2 column.
     * @return java.lang.String
     */
    public java.lang.String getPreColumn2()
    {
        return this.preColumn2;
    }

    /**
     * Set the value of the PRE_COLUMN2 column.
     * @param preColumn2
     */
    public void setPreColumn2(java.lang.String preColumn2)
    {
        this.preColumn2 = preColumn2;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CollectType))
            return false;
        CollectType that = (CollectType) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
