/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jul 22 14:57:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.fitech.net.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the M_BUSINESS table. 
 * You can customize the behavior of this class by editing the class, {@link MBusiness()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public  class MBusiness 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer businessId;

    /** The value of the simple nmBusinesssortname property. */
    private java.lang.String businessName;

    /** The value of the simple nmNote property. */
    private java.lang.String businessNote;

    private java.util.Set  targetDefine;
    public java.util.Set getTargetDefine() {
		return targetDefine;
	}

	public void setTargetDefine(java.util.Set targetDefine) {
		this.targetDefine = targetDefine;
	}

	/**
     * Simple constructor of AbstractMBusiness instances.
     */
    public MBusiness()
    {
    }

	public java.lang.Integer getBusinessId() {
		return businessId;
	}

	public void setBusinessId(java.lang.Integer businessId) {
		this.businessId = businessId;
	}

	public java.lang.String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(java.lang.String businessName) {
		this.businessName = businessName;
	}

	public java.lang.String getBusinessNote() {
		return businessNote;
	}

	public void setBusinessNote(java.lang.String businessNote) {
		this.businessNote = businessNote;
	}

   
   

   
    
}
