/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jun 29 14:32:57 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.fitech.net.hibernate;
import java.io.Serializable;

/**
 * A class that represents a row in the ORG_TYPE table. 
 * You can customize the behavior of this class by editing the class, {@link OrgType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class TargetRange 
    implements Serializable
{
   
    /** The composite primary key value. */
    private java.lang.Integer id;
    private java.lang.String orgId;
    private Integer targetDefineId;
    
   
    /**
     * Simple constructor of AbstractOrgType instances.
     */
    public TargetRange()
    {
    }

    /**
     * Constructor of AbstractOrgType instances given a simple primary key.
     * @param orgTypeId
     */
    public TargetRange(java.lang.Integer Id)
    {
        this.setId(Id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
   

	public java.lang.Integer getId() {
		return id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getOrgId() {
		return orgId;
	}

	public void setOrgId(java.lang.String orgId) {
		this.orgId = orgId;
	}

	public Integer getTargetDefineId() {
		return targetDefineId;
	}

	public void setTargetDefineId(Integer targetDefineId) {
		this.targetDefineId = targetDefineId;
	}

   
}
