
package com.cbrc.auth.adapter;

import java.util.ArrayList;
import java.util.List;

import net.sf.hibernate.Query;
import net.sf.hibernate.Session;

import com.cbrc.auth.form.MBankLevelForm;
import com.cbrc.auth.hibernate.MBankLevel;
import com.cbrc.smis.dao.DBConn;
import com.cbrc.smis.util.FitechException;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MPurView data (i.e. 
 * com.cbrc.auth.form.MPurViewForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMBankLevelDelegate {
    private static FitechException log = new FitechException(StrutsMBankLevelDelegate.class);

    public static List select(){
    	List result = null;
    	DBConn conn = null;
    	Session session = null;
    	try{
    		conn = new DBConn();
			session = conn.openSession();    			
			String hql = "from MBankLevel";
			
			Query query = session.createQuery(hql);
			List list = query.list();
			if(list != null && list.size() > 0){
				result = new ArrayList();
				for(int i=0;i<list.size();i++){					
					MBankLevel mBankLevel = (MBankLevel)list.get(i);
					MBankLevelForm mBankLevelForm = new MBankLevelForm();
					TranslatorUtil.copyPersistenceToVo(mBankLevel,mBankLevelForm);
					result.add(mBankLevelForm);
				}
			}
    	}catch(Exception ex){
    		result = null;
    		log.printStackTrace(ex);
    	}finally{
    		if(conn != null) conn.closeSession();
    	}
    	return result;
    }    
}
