/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Dec 20 10:15:11 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.cbrc.auth.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the M_BANK_LEVEL table. 
 * You can customize the behavior of this class by editing the class, {@link MBankLevel()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class MBankLevel implements Serializable{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer bankLevelId;

    /** The value of the mPurBanklevelSet one-to-many association. */
    private java.util.Set MPurBanklevelSet;

    /** The value of the simple bankLevelName property. */
    private java.lang.String bankLevelName;

    /**
     * Simple constructor of AbstractMBankLevel instances.
     */
    public MBankLevel(){
    }

    /**
     * Constructor of AbstractMBankLevel instances given a simple primary key.
     * @param bankLevelId
     */
    public MBankLevel(java.lang.Integer bankLevelId){
        this.setBankLevelId(bankLevelId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getBankLevelId()
    {
        return bankLevelId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param bankLevelId
     */
    public void setBankLevelId(java.lang.Integer bankLevelId)
    {
        this.hashValue = 0;
        this.bankLevelId = bankLevelId;
    }

    /**
     * Return the value of the BANK_LEVEL_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getBankLevelName()
    {
        return this.bankLevelName;
    }

    /**
     * Set the value of the BANK_LEVEL_NAME column.
     * @param bankLevelName
     */
    public void setBankLevelName(java.lang.String bankLevelName)
    {
        this.bankLevelName = bankLevelName;
    }

    /**
     * Return the value of the BANK_LEVEL_ID collection.
     * @return MPurBanklevel
     */
    public java.util.Set getMPurBanklevelSet() {
		return this.MPurBanklevelSet;
	}

    /**
     * Set the value of the BANK_LEVEL_ID collection.
     * @param mPurBanklevelSet
     */ 
	public void setMPurBanklevelSet(java.util.Set purBanklevelSet) {
		this.MPurBanklevelSet = purBanklevelSet;
	}

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof MBankLevel))
            return false;
        MBankLevel that = (MBankLevel) rhs;
        if (this.getBankLevelId() == null || that.getBankLevelId() == null)
            return false;
        return (this.getBankLevelId().equals(that.getBankLevelId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int bankLevelIdValue = this.getBankLevelId() == null ? 0 : this.getBankLevelId().hashCode();
            result = result * 37 + bankLevelIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
