package com.cbrc.smis.hibernate;
/**
 * SysParameter generated by MyEclipse Persistence Tools
 */

public class SysParameter implements java.io.Serializable
{

	// Fields

	private String parName;

	private String parType;

	private Integer parValue;

	private String description;

	// Constructors

	/** default constructor */
	public SysParameter()
	{
	}

	/** minimal constructor */
	public SysParameter(String parName, String parType, Integer parValue)
	{
		this.parName = parName;
		this.parType = parType;
		this.parValue = parValue;
	}

	/** full constructor */
	public SysParameter(String parName, String parType, Integer parValue, String description)
	{
		this.parName = parName;
		this.parType = parType;
		this.parValue = parValue;
		this.description = description;
	}

	// Property accessors

	public String getParName()
	{
		return this.parName;
	}

	public void setParName(String parName)
	{
		this.parName = parName;
	}

	public String getParType()
	{
		return this.parType;
	}

	public void setParType(String parType)
	{
		this.parType = parType;
	}

	public Integer getParValue()
	{
		return this.parValue;
	}

	public void setParValue(Integer parValue)
	{
		this.parValue = parValue;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

}