
package com.cbrc.org.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MSupvOrg data (i.e. 
 * com.cbrc.org.form.MSupvOrgForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMSupvOrgDelegate {


   /**
    * Create a new com.cbrc.org.form.MSupvOrgForm object and persist (i.e. insert) it.
    *
    * @param   mSupvOrgForm   The object containing the data for the new com.cbrc.org.form.MSupvOrgForm object
    * @exception   Exception   If the new com.cbrc.org.form.MSupvOrgForm object cannot be created or persisted.
    */
   public static com.cbrc.org.form.MSupvOrgForm create (com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = new com.cbrc.org.hibernate.MSupvOrg ();
      TranslatorUtil.copyVoToPersistence(mSupvOrgPersistence, mSupvOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: mSupvOrgPersistence = (com.cbrc.org.hibernate.MSupvOrg)session.save(mSupvOrgPersistence);
session.save(mSupvOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mSupvOrgPersistence, mSupvOrgForm);
      return mSupvOrgForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.org.form.MSupvOrgForm object.
    *
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.org.form.MSupvOrgForm object cannot be updated/persisted.
    */
   public static com.cbrc.org.form.MSupvOrgForm update (com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = new com.cbrc.org.hibernate.MSupvOrg ();
      TranslatorUtil.copyVoToPersistence(mSupvOrgPersistence, mSupvOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(mSupvOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mSupvOrgPersistence, mSupvOrgForm);
      return mSupvOrgForm;
   }

   /**
    * Retrieve an existing com.cbrc.org.form.MSupvOrgForm object for editing.
    *
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.org.form.MSupvOrgForm object cannot be retrieved.
    */
   public static com.cbrc.org.form.MSupvOrgForm edit (com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = new com.cbrc.org.hibernate.MSupvOrg ();
      TranslatorUtil.copyVoToPersistence(mSupvOrgPersistence, mSupvOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
mSupvOrgPersistence = (com.cbrc.org.hibernate.MSupvOrg)session.load(com.cbrc.org.hibernate.MSupvOrg.class, mSupvOrgPersistence.getOrgId());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mSupvOrgPersistence, mSupvOrgForm);
      return mSupvOrgForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.org.form.MSupvOrgForm object.
    *
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.org.form.MSupvOrgForm object cannot be removed.
    */  
   public static void remove (com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = new com.cbrc.org.hibernate.MSupvOrg ();
      TranslatorUtil.copyVoToPersistence(mSupvOrgPersistence, mSupvOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
mSupvOrgPersistence = (com.cbrc.org.hibernate.MSupvOrg)session.load(com.cbrc.org.hibernate.MSupvOrg.class, mSupvOrgPersistence.getOrgId());
session.delete(mSupvOrgPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.org.form.MSupvOrgForm objects.
    *
    * @exception   Exception   If the com.cbrc.org.form.MSupvOrgForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MSupvOrg"));
tx.commit();
session.close();
      ArrayList mSupvOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MSupvOrgForm mSupvOrgFormTemp = new com.cbrc.org.form.MSupvOrgForm();
         com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = (com.cbrc.org.hibernate.MSupvOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mSupvOrgPersistence, mSupvOrgFormTemp);
         mSupvOrg_vos.add(mSupvOrgFormTemp);
      }
      retVals = mSupvOrg_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.org.form.MSupvOrgForm objects for editing.
    *
    * @param   mSupvOrgForm   The com.cbrc.org.form.MSupvOrgForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.org.form.MSupvOrgForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.org.form.MSupvOrgForm mSupvOrgForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MSupvOrg as obj1 where obj1.supvOrgName='" + mSupvOrgForm.getSupvOrgName() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MSupvOrg as obj1 where obj1.priorOrgId='" + mSupvOrgForm.getPriorOrgId() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MSupvOrg as obj1 where obj1.orgCode='" + mSupvOrgForm.getOrgCode() + "'"));
tx.commit();
session.close();
      ArrayList mSupvOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MSupvOrgForm mSupvOrgFormTemp = new com.cbrc.org.form.MSupvOrgForm();
         com.cbrc.org.hibernate.MSupvOrg mSupvOrgPersistence = (com.cbrc.org.hibernate.MSupvOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mSupvOrgPersistence, mSupvOrgFormTemp);
         mSupvOrg_vos.add(mSupvOrgFormTemp);
      }
      retVals = mSupvOrg_vos;
      return retVals;
   }

}
