
package com.cbrc.org.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for MVirtuOrg data (i.e. 
 * com.cbrc.org.form.MVirtuOrgForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsMVirtuOrgDelegate {


   /**
    * Create a new com.cbrc.org.form.MVirtuOrgForm object and persist (i.e. insert) it.
    *
    * @param   mVirtuOrgForm   The object containing the data for the new com.cbrc.org.form.MVirtuOrgForm object
    * @exception   Exception   If the new com.cbrc.org.form.MVirtuOrgForm object cannot be created or persisted.
    */
   public static com.cbrc.org.form.MVirtuOrgForm create (com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = new com.cbrc.org.hibernate.MVirtuOrg ();
      TranslatorUtil.copyVoToPersistence(mVirtuOrgPersistence, mVirtuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: mVirtuOrgPersistence = (com.cbrc.org.hibernate.MVirtuOrg)session.save(mVirtuOrgPersistence);
session.save(mVirtuOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mVirtuOrgPersistence, mVirtuOrgForm);
      return mVirtuOrgForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.org.form.MVirtuOrgForm object.
    *
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.org.form.MVirtuOrgForm object cannot be updated/persisted.
    */
   public static com.cbrc.org.form.MVirtuOrgForm update (com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = new com.cbrc.org.hibernate.MVirtuOrg ();
      TranslatorUtil.copyVoToPersistence(mVirtuOrgPersistence, mVirtuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(mVirtuOrgPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mVirtuOrgPersistence, mVirtuOrgForm);
      return mVirtuOrgForm;
   }

   /**
    * Retrieve an existing com.cbrc.org.form.MVirtuOrgForm object for editing.
    *
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.org.form.MVirtuOrgForm object cannot be retrieved.
    */
   public static com.cbrc.org.form.MVirtuOrgForm edit (com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = new com.cbrc.org.hibernate.MVirtuOrg ();
      TranslatorUtil.copyVoToPersistence(mVirtuOrgPersistence, mVirtuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
mVirtuOrgPersistence = (com.cbrc.org.hibernate.MVirtuOrg)session.load(com.cbrc.org.hibernate.MVirtuOrg.class, mVirtuOrgPersistence.getOrgId());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(mVirtuOrgPersistence, mVirtuOrgForm);
      return mVirtuOrgForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.org.form.MVirtuOrgForm object.
    *
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.org.form.MVirtuOrgForm object cannot be removed.
    */  
   public static void remove (com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = new com.cbrc.org.hibernate.MVirtuOrg ();
      TranslatorUtil.copyVoToPersistence(mVirtuOrgPersistence, mVirtuOrgForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
mVirtuOrgPersistence = (com.cbrc.org.hibernate.MVirtuOrg)session.load(com.cbrc.org.hibernate.MVirtuOrg.class, mVirtuOrgPersistence.getOrgId());
session.delete(mVirtuOrgPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.org.form.MVirtuOrgForm objects.
    *
    * @exception   Exception   If the com.cbrc.org.form.MVirtuOrgForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg"));
tx.commit();
session.close();
      ArrayList mVirtuOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MVirtuOrgForm mVirtuOrgFormTemp = new com.cbrc.org.form.MVirtuOrgForm();
         com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = (com.cbrc.org.hibernate.MVirtuOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mVirtuOrgPersistence, mVirtuOrgFormTemp);
         mVirtuOrg_vos.add(mVirtuOrgFormTemp);
      }
      retVals = mVirtuOrg_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.org.form.MVirtuOrgForm objects for editing.
    *
    * @param   mVirtuOrgForm   The com.cbrc.org.form.MVirtuOrgForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.org.form.MVirtuOrgForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.org.form.MVirtuOrgForm mVirtuOrgForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg as obj1 where obj1.virtualOrgName='" + mVirtuOrgForm.getVirtualOrgName() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg as obj1 where obj1.startDate='" + mVirtuOrgForm.getStartDate() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg as obj1 where obj1.endDate='" + mVirtuOrgForm.getEndDate() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg as obj1 where obj1.orgCode='" + mVirtuOrgForm.getOrgCode() + "'"));
retVals.addAll(session.find("from com.cbrc.org.hibernate.MVirtuOrg as obj1 where obj1.virtuTypeId='" + mVirtuOrgForm.getVirtuTypeId() + "'"));
tx.commit();
session.close();
      ArrayList mVirtuOrg_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.org.form.MVirtuOrgForm mVirtuOrgFormTemp = new com.cbrc.org.form.MVirtuOrgForm();
         com.cbrc.org.hibernate.MVirtuOrg mVirtuOrgPersistence = (com.cbrc.org.hibernate.MVirtuOrg)it.next();
         TranslatorUtil.copyPersistenceToVo(mVirtuOrgPersistence, mVirtuOrgFormTemp);
         mVirtuOrg_vos.add(mVirtuOrgFormTemp);
      }
      retVals = mVirtuOrg_vos;
      return retVals;
   }

}
