
package com.cbrc.smis.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for PolicyExecDetail data (i.e. 
 * com.cbrc.smis.form.PolicyExecDetailForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsPolicyExecDetailDelegate {


   /**
    * Create a new com.cbrc.smis.form.PolicyExecDetailForm object and persist (i.e. insert) it.
    *
    * @param   policyExecDetailForm   The object containing the data for the new com.cbrc.smis.form.PolicyExecDetailForm object
    * @exception   Exception   If the new com.cbrc.smis.form.PolicyExecDetailForm object cannot be created or persisted.
    */
   public static com.cbrc.smis.form.PolicyExecDetailForm create (com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = new com.cbrc.smis.hibernate.PolicyExecDetail ();
      TranslatorUtil.copyVoToPersistence(policyExecDetailPersistence, policyExecDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: policyExecDetailPersistence = (com.cbrc.smis.hibernate.PolicyExecDetail)session.save(policyExecDetailPersistence);
session.save(policyExecDetailPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(policyExecDetailPersistence, policyExecDetailForm);
      return policyExecDetailForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.smis.form.PolicyExecDetailForm object.
    *
    * @param   policyExecDetailForm   The com.cbrc.smis.form.PolicyExecDetailForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.smis.form.PolicyExecDetailForm object cannot be updated/persisted.
    */
   public static com.cbrc.smis.form.PolicyExecDetailForm update (com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = new com.cbrc.smis.hibernate.PolicyExecDetail ();
      TranslatorUtil.copyVoToPersistence(policyExecDetailPersistence, policyExecDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(policyExecDetailPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(policyExecDetailPersistence, policyExecDetailForm);
      return policyExecDetailForm;
   }

   /**
    * Retrieve an existing com.cbrc.smis.form.PolicyExecDetailForm object for editing.
    *
    * @param   policyExecDetailForm   The com.cbrc.smis.form.PolicyExecDetailForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.smis.form.PolicyExecDetailForm object cannot be retrieved.
    */
   public static com.cbrc.smis.form.PolicyExecDetailForm edit (com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = new com.cbrc.smis.hibernate.PolicyExecDetail ();
      TranslatorUtil.copyVoToPersistence(policyExecDetailPersistence, policyExecDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(policyExecDetailPersistence, policyExecDetailForm);
      return policyExecDetailForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.smis.form.PolicyExecDetailForm object.
    *
    * @param   policyExecDetailForm   The com.cbrc.smis.form.PolicyExecDetailForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.smis.form.PolicyExecDetailForm object cannot be removed.
    */  
   public static void remove (com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = new com.cbrc.smis.hibernate.PolicyExecDetail ();
      TranslatorUtil.copyVoToPersistence(policyExecDetailPersistence, policyExecDetailForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
session.delete(policyExecDetailPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.smis.form.PolicyExecDetailForm objects.
    *
    * @exception   Exception   If the com.cbrc.smis.form.PolicyExecDetailForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.PolicyExecDetail"));
tx.commit();
session.close();
      ArrayList policyExecDetail_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailFormTemp = new com.cbrc.smis.form.PolicyExecDetailForm();
         com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = (com.cbrc.smis.hibernate.PolicyExecDetail)it.next();
         TranslatorUtil.copyPersistenceToVo(policyExecDetailPersistence, policyExecDetailFormTemp);
         policyExecDetail_vos.add(policyExecDetailFormTemp);
      }
      retVals = policyExecDetail_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.smis.form.PolicyExecDetailForm objects for editing.
    *
    * @param   policyExecDetailForm   The com.cbrc.smis.form.PolicyExecDetailForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.smis.form.PolicyExecDetailForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.PolicyExecDetail as obj1 where obj1.execTime='" + policyExecDetailForm.getExecTime() + "'"));
tx.commit();
session.close();
      ArrayList policyExecDetail_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailFormTemp = new com.cbrc.smis.form.PolicyExecDetailForm();
         com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = (com.cbrc.smis.hibernate.PolicyExecDetail)it.next();
         TranslatorUtil.copyPersistenceToVo(policyExecDetailPersistence, policyExecDetailFormTemp);
         policyExecDetail_vos.add(policyExecDetailFormTemp);
      }
      retVals = policyExecDetail_vos;
      return retVals;
   }

   /**
    * This method will return all objects referenced by Policy
    */
   public static List getPolicy(com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      List retVals = new ArrayList();
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = null;
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
retVals.add(policyExecDetailPersistence.getPolicy());
      ArrayList POLICY_ID_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.PolicyForm POLICY_ID_Temp = new com.cbrc.smis.form.PolicyForm();
         com.cbrc.smis.hibernate.Policy POLICY_ID_PO = (com.cbrc.smis.hibernate.Policy)it.next();
         TranslatorUtil.copyPersistenceToVo(POLICY_ID_PO, POLICY_ID_Temp);
         POLICY_ID_vos.add(POLICY_ID_Temp);
      }
      retVals = POLICY_ID_vos;
      return retVals;
    }
   /**
    * This method will return all objects referenced by ReportIn
    */
   public static List getReportIn(com.cbrc.smis.form.PolicyExecDetailForm policyExecDetailForm) throws Exception {
      List retVals = new ArrayList();
      com.cbrc.smis.hibernate.PolicyExecDetail policyExecDetailPersistence = null;
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
retVals.add(policyExecDetailPersistence.getReportIn());
      ArrayList REP_IN_ID_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.ReportInForm REP_IN_ID_Temp = new com.cbrc.smis.form.ReportInForm();
         com.cbrc.smis.hibernate.ReportIn REP_IN_ID_PO = (com.cbrc.smis.hibernate.ReportIn)it.next();
         TranslatorUtil.copyPersistenceToVo(REP_IN_ID_PO, REP_IN_ID_Temp);
         REP_IN_ID_vos.add(REP_IN_ID_Temp);
      }
      retVals = REP_IN_ID_vos;
      return retVals;
    }
}
