
package com.cbrc.smis.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for ColToFormu data (i.e. 
 * com.cbrc.smis.form.ColToFormuForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsColToFormuDelegate {


   /**
    * Create a new com.cbrc.smis.form.ColToFormuForm object and persist (i.e. insert) it.
    *
    * @param   colToFormuForm   The object containing the data for the new com.cbrc.smis.form.ColToFormuForm object
    * @exception   Exception   If the new com.cbrc.smis.form.ColToFormuForm object cannot be created or persisted.
    */
   public static com.cbrc.smis.form.ColToFormuForm create (com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = new com.cbrc.smis.hibernate.ColToFormu ();
      TranslatorUtil.copyVoToPersistence(colToFormuPersistence, colToFormuForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: colToFormuPersistence = (com.cbrc.smis.hibernate.ColToFormu)session.save(colToFormuPersistence);
session.save(colToFormuPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(colToFormuPersistence, colToFormuForm);
      return colToFormuForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.smis.form.ColToFormuForm object.
    *
    * @param   colToFormuForm   The com.cbrc.smis.form.ColToFormuForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.smis.form.ColToFormuForm object cannot be updated/persisted.
    */
   public static com.cbrc.smis.form.ColToFormuForm update (com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = new com.cbrc.smis.hibernate.ColToFormu ();
      TranslatorUtil.copyVoToPersistence(colToFormuPersistence, colToFormuForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(colToFormuPersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(colToFormuPersistence, colToFormuForm);
      return colToFormuForm;
   }

   /**
    * Retrieve an existing com.cbrc.smis.form.ColToFormuForm object for editing.
    *
    * @param   colToFormuForm   The com.cbrc.smis.form.ColToFormuForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.smis.form.ColToFormuForm object cannot be retrieved.
    */
   public static com.cbrc.smis.form.ColToFormuForm edit (com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = new com.cbrc.smis.hibernate.ColToFormu ();
      TranslatorUtil.copyVoToPersistence(colToFormuPersistence, colToFormuForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(colToFormuPersistence, colToFormuForm);
      return colToFormuForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.smis.form.ColToFormuForm object.
    *
    * @param   colToFormuForm   The com.cbrc.smis.form.ColToFormuForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.smis.form.ColToFormuForm object cannot be removed.
    */  
   public static void remove (com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = new com.cbrc.smis.hibernate.ColToFormu ();
      TranslatorUtil.copyVoToPersistence(colToFormuPersistence, colToFormuForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
session.delete(colToFormuPersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.smis.form.ColToFormuForm objects.
    *
    * @exception   Exception   If the com.cbrc.smis.form.ColToFormuForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.ColToFormu"));
tx.commit();
session.close();
      ArrayList colToFormu_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.ColToFormuForm colToFormuFormTemp = new com.cbrc.smis.form.ColToFormuForm();
         com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = (com.cbrc.smis.hibernate.ColToFormu)it.next();
         TranslatorUtil.copyPersistenceToVo(colToFormuPersistence, colToFormuFormTemp);
         colToFormu_vos.add(colToFormuFormTemp);
      }
      retVals = colToFormu_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.smis.form.ColToFormuForm objects for editing.
    *
    * @param   colToFormuForm   The com.cbrc.smis.form.ColToFormuForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.smis.form.ColToFormuForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
      ArrayList colToFormu_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.ColToFormuForm colToFormuFormTemp = new com.cbrc.smis.form.ColToFormuForm();
         com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = (com.cbrc.smis.hibernate.ColToFormu)it.next();
         TranslatorUtil.copyPersistenceToVo(colToFormuPersistence, colToFormuFormTemp);
         colToFormu_vos.add(colToFormuFormTemp);
      }
      retVals = colToFormu_vos;
      return retVals;
   }

   /**
    * This method will return all objects referenced by MCellFormu
    */
   public static List getMCellFormu(com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      List retVals = new ArrayList();
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = null;
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
retVals.add(colToFormuPersistence.getMCellFormu());
      ArrayList CELL_FORMU_ID_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.MCellFormuForm CELL_FORMU_ID_Temp = new com.cbrc.smis.form.MCellFormuForm();
         com.cbrc.smis.hibernate.MCellFormu CELL_FORMU_ID_PO = (com.cbrc.smis.hibernate.MCellFormu)it.next();
         TranslatorUtil.copyPersistenceToVo(CELL_FORMU_ID_PO, CELL_FORMU_ID_Temp);
         CELL_FORMU_ID_vos.add(CELL_FORMU_ID_Temp);
      }
      retVals = CELL_FORMU_ID_vos;
      return retVals;
    }
   /**
    * This method will return all objects referenced by MChildReport
    */
   public static List getMChildReport(com.cbrc.smis.form.ColToFormuForm colToFormuForm) throws Exception {
      List retVals = new ArrayList();
      com.cbrc.smis.hibernate.ColToFormu colToFormuPersistence = null;
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
tx.commit();
session.close();
retVals.add(colToFormuPersistence.getMChildReport());
      ArrayList CHILD_REP_ID_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.MChildReportForm CHILD_REP_ID_Temp = new com.cbrc.smis.form.MChildReportForm();
         com.cbrc.smis.hibernate.MChildReport CHILD_REP_ID_PO = (com.cbrc.smis.hibernate.MChildReport)it.next();
         TranslatorUtil.copyPersistenceToVo(CHILD_REP_ID_PO, CHILD_REP_ID_Temp);
         CHILD_REP_ID_vos.add(CHILD_REP_ID_Temp);
      }
      retVals = CHILD_REP_ID_vos;
      return retVals;
    }
}
