
package com.cbrc.smis.adapter;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of hibernate. 
 * It has a set of methods to handle persistence for CalendarType data (i.e. 
 * com.cbrc.smis.form.CalendarTypeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsCalendarTypeDelegate {


   /**
    * Create a new com.cbrc.smis.form.CalendarTypeForm object and persist (i.e. insert) it.
    *
    * @param   calendarTypeForm   The object containing the data for the new com.cbrc.smis.form.CalendarTypeForm object
    * @exception   Exception   If the new com.cbrc.smis.form.CalendarTypeForm object cannot be created or persisted.
    */
   public static com.cbrc.smis.form.CalendarTypeForm create (com.cbrc.smis.form.CalendarTypeForm calendarTypeForm) throws Exception {
      com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = new com.cbrc.smis.hibernate.CalendarType ();
      TranslatorUtil.copyVoToPersistence(calendarTypePersistence, calendarTypeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO error?: calendarTypePersistence = (com.cbrc.smis.hibernate.CalendarType)session.save(calendarTypePersistence);
session.save(calendarTypePersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(calendarTypePersistence, calendarTypeForm);
      return calendarTypeForm;
   }

   /**
    * Update (i.e. persist) an existing com.cbrc.smis.form.CalendarTypeForm object.
    *
    * @param   calendarTypeForm   The com.cbrc.smis.form.CalendarTypeForm object containing the data to be updated
    * @exception   Exception   If the com.cbrc.smis.form.CalendarTypeForm object cannot be updated/persisted.
    */
   public static com.cbrc.smis.form.CalendarTypeForm update (com.cbrc.smis.form.CalendarTypeForm calendarTypeForm) throws Exception {
      com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = new com.cbrc.smis.hibernate.CalendarType ();
      TranslatorUtil.copyVoToPersistence(calendarTypePersistence, calendarTypeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
session.update(calendarTypePersistence);
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(calendarTypePersistence, calendarTypeForm);
      return calendarTypeForm;
   }

   /**
    * Retrieve an existing com.cbrc.smis.form.CalendarTypeForm object for editing.
    *
    * @param   calendarTypeForm   The com.cbrc.smis.form.CalendarTypeForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.cbrc.smis.form.CalendarTypeForm object cannot be retrieved.
    */
   public static com.cbrc.smis.form.CalendarTypeForm edit (com.cbrc.smis.form.CalendarTypeForm calendarTypeForm) throws Exception {
      com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = new com.cbrc.smis.hibernate.CalendarType ();
      TranslatorUtil.copyVoToPersistence(calendarTypePersistence, calendarTypeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
calendarTypePersistence = (com.cbrc.smis.hibernate.CalendarType)session.load(com.cbrc.smis.hibernate.CalendarType.class, calendarTypePersistence.getCalTypeId());
tx.commit();
session.close();
      TranslatorUtil.copyPersistenceToVo(calendarTypePersistence, calendarTypeForm);
      return calendarTypeForm;
   }

   /**
    * Remove (delete) an existing com.cbrc.smis.form.CalendarTypeForm object.
    *
    * @param   calendarTypeForm   The com.cbrc.smis.form.CalendarTypeForm object containing the data to be deleted.
    * @exception   Exception   If the com.cbrc.smis.form.CalendarTypeForm object cannot be removed.
    */  
   public static void remove (com.cbrc.smis.form.CalendarTypeForm calendarTypeForm) throws Exception {
      com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = new com.cbrc.smis.hibernate.CalendarType ();
      TranslatorUtil.copyVoToPersistence(calendarTypePersistence, calendarTypeForm);
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
// TODO: is this really needed?
calendarTypePersistence = (com.cbrc.smis.hibernate.CalendarType)session.load(com.cbrc.smis.hibernate.CalendarType.class, calendarTypePersistence.getCalTypeId());
session.delete(calendarTypePersistence);
tx.commit();
session.close();
   }

   /**
    * Retrieve all existing com.cbrc.smis.form.CalendarTypeForm objects.
    *
    * @exception   Exception   If the com.cbrc.smis.form.CalendarTypeForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.CalendarType"));
tx.commit();
session.close();
      ArrayList calendarType_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.CalendarTypeForm calendarTypeFormTemp = new com.cbrc.smis.form.CalendarTypeForm();
         com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = (com.cbrc.smis.hibernate.CalendarType)it.next();
         TranslatorUtil.copyPersistenceToVo(calendarTypePersistence, calendarTypeFormTemp);
         calendarType_vos.add(calendarTypeFormTemp);
      }
      retVals = calendarType_vos;
      return retVals;
   }

   /**
    * Retrieve a set of existing com.cbrc.smis.form.CalendarTypeForm objects for editing.
    *
    * @param   calendarTypeForm   The com.cbrc.smis.form.CalendarTypeForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.cbrc.smis.form.CalendarTypeForm objects cannot be retrieved.
    */
   public static List select (com.cbrc.smis.form.CalendarTypeForm calendarTypeForm) throws Exception {
      List retVals = new ArrayList();
javax.naming.InitialContext ctx = new javax.naming.InitialContext();
// TODO: Make adapter get SessionFactory jndi name by ant task argument?
net.sf.hibernate.SessionFactory factory = (net.sf.hibernate.SessionFactory)ctx.lookup("java:AirlineHibernateFactory");
net.sf.hibernate.Session session = factory.openSession();
net.sf.hibernate.Transaction tx = session.beginTransaction();
retVals.addAll(session.find("from com.cbrc.smis.hibernate.CalendarType as obj1 where obj1.calTypeName='" + calendarTypeForm.getCalTypeName() + "'"));
tx.commit();
session.close();
      ArrayList calendarType_vos = new ArrayList();
      for (Iterator it = retVals.iterator(); it.hasNext(); ) {
         com.cbrc.smis.form.CalendarTypeForm calendarTypeFormTemp = new com.cbrc.smis.form.CalendarTypeForm();
         com.cbrc.smis.hibernate.CalendarType calendarTypePersistence = (com.cbrc.smis.hibernate.CalendarType)it.next();
         TranslatorUtil.copyPersistenceToVo(calendarTypePersistence, calendarTypeFormTemp);
         calendarType_vos.add(calendarTypeFormTemp);
      }
      retVals = calendarType_vos;
      return retVals;
   }

}
